"""
Django settings for absharProject project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_o*sce-7v=squt58jj0$l=ezgw^!ek$_%8c2##qd^o&7n@4v0h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # main_app
    'channels',
    'user_app',
    'admin_panel',
    'middleAdmin_panel',
    'notifications',

    # 'jalali_date',

    'polls',
    'payment_app',
    'reports',
    #
    # # other_app
    'django_render_partial',
    'sweetify',
    'jalali_date',

    'ckeditor',
    'ckeditor_uploader',  # enables file & image uploads
    'azbankgateways',

]

# AZ_IRANIAN_BANK_GATEWAYS = {
#    'GATEWAYS': {
#        'MELLAT': {
#            'TERMINAL_CODE': '8807710',
#            'USERNAME': '8807710',
#            'PASSWORD': '64728741',
#        },
#    },
#    'DEFAULT': 'MELLAT',
#    'CURRENCY': 'IRR', # اختیاری
#    'TRACKING_CODE_QUERY_PARAM': 'tc', # اختیاری
#    'TRACKING_CODE_LENGTH': 16, # اختیاری
#    'SETTING_VALUE_READER_CLASS': 'azbankgateways.readers.DefaultReader', # اختیاری
#    'BANK_PRIORITIES': [
#    ], # اختیاری
# }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
AUTH_USER_MODEL = 'user_app.User'

ROOT_URLCONF = 'absharProject.urls'

LOGIN_URL_ADMIN = '/admin-panel/login-admin/'
LOGIN_URL_MIDDLE_ADMIN = '/middle-admin-panel/login-middleAdmin/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'absharProject.context_processors.current_house',
            ],
        },
    },
]

# WSGI_APPLICATION = 'absharProject.wsgi.application'
ASGI_APPLICATION = 'absharProject.asgi.application'
#
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_L10N = True
USE_TZ = False
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'  # Use a consistent trailing slash for URL patterns
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Directory for additional static files (e.g., custom JS, CSS)
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Uploaded by users)
MEDIA_URL = '/media/'  # Use a consistent trailing slash
MEDIA_ROOT = BASE_DIR / 'uploads'  # Directory where uploaded files will be stored

CKEDITOR_UPLOAD_PATH = "uploads/articles/"  # همان فولدری که ساختی
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'filebrowserBrowseUrl': '/ckeditor/browse/',
        'contentsCss': ['/static/admin_panel/css/ckeditor_fa.css'],

        'height': 300,
        'width': 'auto',
        'extraPlugins': ','.join([
            'uploadimage',  # برای آپلود تصویر داخل متن
            'justify',  # برای Justify یا تنظیم چپ/راست
            'font',  # انتخاب فونت
            'colorbutton',  # رنگ متن
            'embed',  # Embed ویدیو
            'emoji',
            'autocomplete',  # وابسته به emoji
            'textmatch',  # وابسته به emoji

        ]),

        'font_names': 'Vazir;VazirB1;VazirB2;VazirB3;VazirB4;VazirBold;Tahoma;Arial;Sans-Serif;',
        'removePlugins': 'stylesheetparser,exportpdf,clipboard',
        'language': 'fa',
        'direction': 'rtl',
        'contentsLangDirection': 'rtl',
        'contentsLanguage': 'fa',
        'tabSpaces': 4,
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

Kavenegar_API = '795A7476367A46796858526E6E4744576A7A516E7750696E6C65654E654E525835784C38716437515270453D'

JALALI_DATE_DEFAULTS = {
    # if change it to true then all dates of the list_display will convert to the Jalali.
    'LIST_DISPLAY_AUTO_CONVERT': False,
    'Strftime': {
        'date': '%y/%m/%d',
        'datetime': '%H:%M:%S _ %y/%m/%d',
    },
    'Static': {
        'js': [
            'admin/js/django_jalali.min.js',
        ],
        'css': {
            'all': [
                'admin/css/django_jalali.min.css',
            ]
        }
    },
}
