# Generated by Django 5.2 on 2025-04-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='عنوان')),
                ('slug', models.SlugField(default='', max_length=200, null=True, verbose_name='عنوان در url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
        ),
    ]
