# Generated by Django 5.2 on 2025-12-28 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='areacharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areaCharge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='areachargecalc',
            name='area_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_charge_amount', to='admin_panel.areacharge'),
        ),
        migrations.AddField(
            model_name='areachargecalc',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='areachargecalc',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_area', to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='areachargecalc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_area', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonarea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonareacalc',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonareacalc',
            name='fix_person_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fix_person_area', to='admin_panel.chargebyfixpersonarea'),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonareacalc',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_by_fix_person_area', to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonareacalc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_by_fix_person_area', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargebypersonarea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargebypersonareacalc',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='chargebypersonareacalc',
            name='person_area_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_area_charge', to='admin_panel.chargebypersonarea'),
        ),
        migrations.AddField(
            model_name='chargebypersonareacalc',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_by_person_area', to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='chargebypersonareacalc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_by_person_area', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargefixvariable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargefixvariablecalc',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='chargefixvariablecalc',
            name='fix_variable_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fix_variable_charge', to='admin_panel.chargefixvariable'),
        ),
        migrations.AddField(
            model_name='chargefixvariablecalc',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_calc_fix', to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='chargefixvariablecalc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_calc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargemaster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_masters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargefixvariable',
            name='charge_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variabke_charge', to='admin_panel.chargemaster'),
        ),
        migrations.AddField(
            model_name='chargebypersonarea',
            name='charge_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_area_charge', to='admin_panel.chargemaster'),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonarea',
            name='charge_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_person_area_charge', to='admin_panel.chargemaster'),
        ),
        migrations.AddField(
            model_name='areacharge',
            name='charge_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_charge', to='admin_panel.chargemaster'),
        ),
        migrations.AddField(
            model_name='expense',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='admin_panel.expensecategory', verbose_name='گروه'),
        ),
        migrations.AddField(
            model_name='expensedocument',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.expense'),
        ),
        migrations.AddField(
            model_name='fixareacharge',
            name='charge_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_area_charge', to='admin_panel.chargemaster'),
        ),
        migrations.AddField(
            model_name='fixareacharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_fixed_area', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixareachargecalc',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='fixareachargecalc',
            name='fix_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_area_charge', to='admin_panel.fixareacharge'),
        ),
        migrations.AddField(
            model_name='fixareachargecalc',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_fix_area', to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='fixareachargecalc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_fix_area', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixcharge',
            name='charge_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_charges', to='admin_panel.chargemaster'),
        ),
        migrations.AddField(
            model_name='fixcharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixCharge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixedchargecalc',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='fixedchargecalc',
            name='fix_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_charge_amount', to='admin_panel.fixcharge'),
        ),
        migrations.AddField(
            model_name='fixedchargecalc',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_fix', to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='fixedchargecalc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_fix', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixpersoncharge',
            name='charge_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_person_charge', to='admin_panel.chargemaster'),
        ),
        migrations.AddField(
            model_name='fixpersoncharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='fix_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_person_charge', to='admin_panel.fixpersoncharge'),
        ),
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_fix_person', to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_fix_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fund',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='fund',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='fund',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='fund',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='income',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='admin_panel.incomecategory', verbose_name='گروه'),
        ),
        migrations.AddField(
            model_name='incomedocument',
            name='income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.income'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancedocument',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.maintenance'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagetouser',
            name='units',
            field=models.ManyToManyField(related_name='messages', to='user_app.unit', verbose_name='واحدها'),
        ),
        migrations.AddField(
            model_name='messagetouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='admin_panel.messagetouser'),
        ),
        migrations.AddField(
            model_name='paymoney',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='paymoney',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='paymoney',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paydocument',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.paymoney'),
        ),
        migrations.AddField(
            model_name='personcharge',
            name='charge_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_charge', to='admin_panel.chargemaster'),
        ),
        migrations.AddField(
            model_name='personcharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargePerson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personchargecalc',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='personchargecalc',
            name='person_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_charge_amount', to='admin_panel.personcharge'),
        ),
        migrations.AddField(
            model_name='personchargecalc',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_person', to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='personchargecalc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.property'),
        ),
        migrations.AddField(
            model_name='receivemoney',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='receivemoney',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='receivemoney',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivedocument',
            name='receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.receivemoney'),
        ),
        migrations.AddField(
            model_name='smsmanagement',
            name='notified_units',
            field=models.ManyToManyField(blank=True, to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='smsmanagement',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_unit', to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='smsmanagement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_charges', to='user_app.bank'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='charge_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_charges', to='admin_panel.chargemaster'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_charges', to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_charges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together={('message', 'user')},
        ),
    ]
