# Generated by Django 5.2 on 2026-06-05 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminfund',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='adminfund',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='adminfund',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_houses', to='user_app.myhouse', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='adminfund',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminmessagetomiddle',
            name='middleAdmins',
            field=models.ManyToManyField(related_name='received_admin_messages', to=settings.AUTH_USER_MODEL, verbose_name='مدیران ساختمان'),
        ),
        migrations.AddField(
            model_name='adminmessagetomiddle',
            name='sender',
            field=models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_admin_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده'),
        ),
        migrations.AddField(
            model_name='adminsmsmanagement',
            name='notified_users',
            field=models.ManyToManyField(blank=True, related_name='admin_sms_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminsmsmanagement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_sms_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.myhouse'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='areacharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankfund',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='bankfund',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='bankfund',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_funds', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='bankfund',
            name='to_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='user_app.bank'),
        ),
        migrations.AddField(
            model_name='bankfund',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks_funds', to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='bankfund',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargebyexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonarea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargebypersonarea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargefixvariable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='civilinstallment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='civilinstallment',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_installment', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='civilinstallment',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='civilmanage',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_civil', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='civilmanage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='civilinstallment',
            name='civil_manage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='admin_panel.civilmanage'),
        ),
        migrations.AddField(
            model_name='civildocument',
            name='civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_documents', to='admin_panel.civilmanage'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.coupon'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='expense',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_expenses', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='admin_panel.expensecategory', verbose_name='گروه'),
        ),
        migrations.AddField(
            model_name='expensedocument',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.expense'),
        ),
        migrations.AddField(
            model_name='fixareacharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixcharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixpersoncharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fund',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='fund',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='fund',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_funds', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='fund',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='fund',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impersonationlog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonated_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impersonationlog',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonated_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='income',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_incomes', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='income',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='admin_panel.incomecategory', verbose_name='گروه'),
        ),
        migrations.AddField(
            model_name='incomedocument',
            name='income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.income'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_maintenance', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancedocument',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.maintenance'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='messagetouser',
            name='notified_units',
            field=models.ManyToManyField(blank=True, related_name='notified_messages', to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='messagetouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='admin_panel.messagetouser'),
        ),
        migrations.AddField(
            model_name='middlemessagereadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='admin_panel.adminmessagetomiddle'),
        ),
        migrations.AddField(
            model_name='middlemessagereadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymoney',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='paymoney',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_payments', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='paymoney',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='paymoney',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paydocument',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.paymoney'),
        ),
        migrations.AddField(
            model_name='personcharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='property',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_property', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.property'),
        ),
        migrations.AddField(
            model_name='receivemoney',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='receivemoney',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_receives', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='receivemoney',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='receivemoney',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivedocument',
            name='receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.receivemoney'),
        ),
        migrations.AddField(
            model_name='sewageinstallment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='sewageinstallment',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_installment_sewage', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='sewageinstallment',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='sewagemanage',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_sewage', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='sewagemanage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sewageinstallment',
            name='sewage_manage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sewage_installments', to='admin_panel.sewagemanage'),
        ),
        migrations.AddField(
            model_name='sewagedocument',
            name='sewage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sewage_documents', to='admin_panel.sewagemanage'),
        ),
        migrations.AddField(
            model_name='smscredit',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_credit', to='user_app.myhouse'),
        ),
        migrations.AddField(
            model_name='smscredit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدیر'),
        ),
        migrations.AddField(
            model_name='smsmanagement',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_sms', to='user_app.myhouse'),
        ),
        migrations.AddField(
            model_name='smsmanagement',
            name='notified_units',
            field=models.ManyToManyField(blank=True, to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='smsmanagement',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_unit', to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='smsmanagement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.coupon'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.myhouse'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_charges', to='user_app.bank'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_charges', to='user_app.myhouse'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='penalty_waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_charges', to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_charges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='admin_panel_code_206340_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['active', 'valid_from', 'valid_to'], name='admin_panel_active_9a6e31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('user', 'coupon')},
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together={('message', 'unit')},
        ),
        migrations.AlterUniqueTogether(
            name='middlemessagereadstatus',
            unique_together={('message', 'user')},
        ),
    ]
