# Generated by Django 5.2 on 2025-12-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixareacharge',
            name='charge_master',
        ),
        migrations.RemoveField(
            model_name='chargebyfixpersonarea',
            name='charge_master',
        ),
        migrations.RemoveField(
            model_name='fixcharge',
            name='charge_master',
        ),
        migrations.RemoveField(
            model_name='chargebypersonarea',
            name='charge_master',
        ),
        migrations.RemoveField(
            model_name='fixpersoncharge',
            name='charge_master',
        ),
        migrations.RemoveField(
            model_name='areacharge',
            name='charge_master',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='charge_master',
        ),
        migrations.RemoveField(
            model_name='personcharge',
            name='charge_master',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='charge_master',
        ),
        migrations.DeleteModel(
            name='ChargeMaster',
        ),
    ]
