# Generated by Django 5.2 on 2025-06-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixcharge',
            name='unit_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
