# Generated by Django 5.2 on 2026-01-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetouser',
            name='units',
        ),
    ]
