# Generated by Django 5.2 on 2025-11-04 19:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='slug',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
