# Generated by Django 5.2 on 2025-06-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_fixpersoncharge_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixpersoncharge',
            name='civil',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='شارژ عمرانی'),
        ),
    ]
