# Generated by Django 5.2 on 2026-05-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscredit',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smscredit',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
