# Generated by Django 5.2 on 2026-06-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_commentsite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentSite',
        ),
    ]
