# Generated by Django 5.2 on 2026-01-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_messagetouser_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='show_in_marquee',
            field=models.BooleanField(default=False),
        ),
    ]
