# Generated by Django 5.2 on 2025-12-30 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_fixareacharge_charge_master_and_more'),
        ('user_app', '0002_myhouse_floor_counts_myhouse_unit_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
    ]
