# Generated by Django 5.2 on 2025-04-25 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_announcement_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ سند')),
                ('doc_no', models.IntegerField(verbose_name='شماره سند')),
                ('description', models.CharField(max_length=4000, verbose_name='شرح')),
                ('amount', models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='قیمت')),
                ('details', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('document', models.FileField(blank=True, null=True, upload_to='images/expense', verbose_name='تصاویر هزینه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.expensecategory', verbose_name='گروه')),
            ],
        ),
    ]
