# Generated by Django 5.2 on 2025-06-05 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_fixcharge_unit_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='areacharge',
            name='payment_deadline',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areacharge',
            name='payment_penalty_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='areacharge',
            name='unit_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacharge',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='areaCharge', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areachargecalc',
            name='payment_deadline_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areachargecalc',
            name='payment_penalty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='areachargecalc',
            name='send_notification_date',
            field=models.DateTimeField(default=1, verbose_name='اعلام شارژ به کاربر'),
            preserve_default=False,
        ),
    ]
