# Generated by Django 5.2 on 2025-06-03 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_announcement_user'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymoney',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='receivemoney',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
    ]
