# Generated by Django 5.2 on 2025-06-06 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_chargebypersonarea_other_cost_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebyfixpersonarea',
            name='other_cost_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سایر هزینه ها'),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonarea',
            name='payment_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonarea',
            name='payment_penalty_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonarea',
            name='unit_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonarea',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargebyfixpersonareacalc',
            name='other_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سایر هزینه ها'),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonareacalc',
            name='payment_deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonareacalc',
            name='payment_penalty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonareacalc',
            name='send_notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='اعلام شارژ به کاربر'),
        ),
    ]
