# Generated by Django 5.2 on 2025-06-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_areacharge_payment_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacharge',
            name='total_area',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
