# Generated by Django 5.2 on 2025-12-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_fund_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='charge_by_area_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='charge_by_person_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='fix_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='fix_area_variable_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='fix_person_variable_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargebyfixpersonarea',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=''),
        ),
    ]
