# Generated by Django 5.2 on 2025-04-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_expensecategory_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='document',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.expensecategory', verbose_name='گروه'),
        ),
        migrations.CreateModel(
            name='ExpenseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images/expense/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.expense')),
            ],
        ),
    ]
