# Generated by Django 5.2 on 2025-06-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_expense_user_expensecategory_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensedocument',
            name='user',
        ),
    ]
