# Generated by Django 5.2 on 2025-12-31 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_unifiedcharge_charge_by_area_amount_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_app', '0002_myhouse_floor_counts_myhouse_unit_counts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='unifiedcharge',
            old_name='charge_by_area_amount',
            new_name='base_amount',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='charge_by_person_amount',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='details',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='fix_amount',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='fix_area_variable_amount',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='fix_person_variable_amount',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='other_cost_amount',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='payment_gateway',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='send_notification',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='send_notification_date',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='title',
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='other_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='penalty_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.bank'),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='charge_type',
            field=models.CharField(choices=[('fix', 'ثابت'), ('area', 'متراژ'), ('person', 'نفر'), ('fix_person', 'ثابت + نفر'), ('fix_area', 'ثابت + متراژ'), ('person_area', 'نفر + متراژ'), ('fix_person_area', 'ثابت + نفر + متراژ'), ('fix_variable', 'ثابت + متغیر')], max_length=30),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='civil',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='payment_deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='penalty_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='total_charge_month',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
