# Generated by Django 5.2 on 2025-04-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_remove_expense_document_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensedocument',
            old_name='file',
            new_name='document',
        ),
    ]
