# Generated by Django 5.2 on 2025-11-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_fund_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
