# Generated by Django 5.2 on 2026-01-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_smscredit_amount_with_tax_adminfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmanagement',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsmanagement',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smsmanagement',
            name='send_notification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
