# Generated by Django 5.2 on 2025-06-08 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_chargefixvariable_payment_deadline_and_more'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedchargecalc',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
            preserve_default=False,
        ),
    ]
