# Generated by Django 5.2 on 2025-12-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_fund_transaction_no'),
        ('user_app', '0009_myhouse_residents_alter_myhouse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmanagement',
            name='notified_units',
            field=models.ManyToManyField(blank=True, to='user_app.unit'),
        ),
    ]
