# Generated by Django 5.2 on 2025-12-31 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_fixcharge_payment_date_alter_fixcharge_civil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='send_notification',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='send_notification_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='اعلام شارژ به کاربر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر با پیامک'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='send_sms_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ پیامک به کاربر'),
            preserve_default=False,
        ),
    ]
