# Generated by Django 5.2 on 2026-01-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_smsmanagement_approved_at_smsmanagement_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmanagement',
            name='sms_per_message',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد پیامک هر متن'),
        ),
        migrations.AddField(
            model_name='smsmanagement',
            name='total_sms_sent',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد کل پیامک مصرف\u200cشده'),
        ),
        migrations.AddField(
            model_name='smsmanagement',
            name='total_units_sent',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد واحدهای ارسال\u200cشده'),
        ),
    ]
