# Generated by Django 5.2 on 2025-06-08 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_fixedchargecalc_bank'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areachargecalc',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargebyfixpersonareacalc',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargebypersonareacalc',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargefixvariablecalc',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixareachargecalc',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personchargecalc',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
            preserve_default=False,
        ),
    ]
