# Generated by Django 5.2 on 2025-12-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_unifiedcharge_send_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedcharge',
            name='send_sms_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پیامک به کاربر'),
        ),
    ]
