# Generated by Django 5.2 on 2026-01-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_smsmanagement_sms_per_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmanagement',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='smsmanagement',
            name='sms_per_message',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smsmanagement',
            name='total_sms_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smsmanagement',
            name='total_units_sent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
