# Generated by Django 5.2 on 2025-12-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_smsmanagement_notified_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedchargecalc',
            name='payment_deadline_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixedchargecalc',
            name='send_notification_date',
            field=models.DateTimeField(verbose_name='اعلام شارژ به کاربر'),
        ),
    ]
