# Generated by Django 5.2 on 2025-04-28 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_remove_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ سند'),
            preserve_default=False,
        ),
    ]
