# Generated by Django 5.2 on 2025-12-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_alter_fixedchargecalc_payment_deadline_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedchargecalc',
            name='payment_penalty_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
