# Generated by Django 5.2 on 2026-01-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_smsmanagement_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='send_sms_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ارسال پیامک'),
        ),
    ]
