# Generated by Django 5.2 on 2026-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_alter_unifiedcharge_send_sms_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='charge_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
