# Generated by Django 5.2 on 2026-01-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_unifiedcharge_charge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedcharge',
            name='base_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='civil',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='other_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='penalty_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='penalty_percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='total_charge_month',
            field=models.IntegerField(),
        ),
    ]
