# Generated by Django 5.2 on 2025-05-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_expense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='admin_panel.expensecategory', verbose_name='گروه'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ سند')),
                ('doc_no', models.IntegerField(verbose_name='شماره سند')),
                ('description', models.CharField(max_length=4000, verbose_name='شرح')),
                ('amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='قیمت')),
                ('details', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='admin_panel.incomecategory', verbose_name='گروه')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='images/income/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.income')),
            ],
        ),
    ]
