# Generated by Django 5.2 on 2025-10-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_alter_areachargecalc_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixcharge',
            name='total_charge_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ کل ماهانه'),
        ),
    ]
