# Generated by Django 5.2 on 2025-12-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_fixedchargecalc_payment_penalty_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedchargecalc',
            name='payment_deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixedchargecalc',
            name='send_notification_date',
            field=models.DateField(verbose_name='اعلام شارژ به کاربر'),
        ),
    ]
