# Generated by Django 5.2 on 2026-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_unifiedcharge_send_sms_unifiedcharge_send_sms_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='sms_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='sms_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='sms_total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
