# Generated by Django 5.2 on 2025-12-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_fixedchargecalc_payment_deadline_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedchargecalc',
            old_name='payment_penalty_amount',
            new_name='payment_penalty_price',
        ),
    ]
