# Generated by Django 5.2 on 2025-05-03 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_incomecategory_alter_expense_category_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='date',
            new_name='doc_date',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='doc_no',
            new_name='doc_number',
        ),
        migrations.RenameField(
            model_name='incomecategory',
            old_name='title',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='incomedocument',
            old_name='document',
            new_name='image',
        ),
    ]
