# Generated by Django 5.2 on 2026-02-05 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_unifiedcharge_sms_count_unifiedcharge_sms_price_and_more'),
        ('user_app', '0011_user_is_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='house',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='user_app.myhouse'),
            preserve_default=False,
        ),
    ]
