# Generated by Django 5.2 on 2026-01-01 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_unifiedcharge_base_amount_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_app', '0002_myhouse_floor_counts_myhouse_unit_counts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='base_amount',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='charge_name',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='other_cost',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='penalty_percent',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='send_sms',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='send_sms_date',
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='charge_by_area_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='charge_by_person_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='details',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='fix_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='fix_area_variable_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='fix_person_variable_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='other_cost_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_charges', to='user_app.bank'),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='charge_type',
            field=models.CharField(choices=[('fixed', 'Fixed Charge'), ('area', 'Area Charge'), ('person', 'Person Charge'), ('fix_person', 'Fixed Person Charge'), ('fix_area', 'Fixed Area Charge'), ('person_area', 'Person Area Charge'), ('fix_person_area', 'Fixed Person Area'), ('fix_variable', 'Variable Fixed Charge')], max_length=50),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='civil',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='شارژ عمرانی'),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='payment_deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='مهلت پرداخت'),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='penalty_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='send_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='send_notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ارسال اعلان'),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='total_charge_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_charges', to='user_app.unit'),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_charges', to=settings.AUTH_USER_MODEL),
        ),
    ]
