# Generated by Django 5.2 on 2025-10-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_fixcharge_total_charge_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areachargecalc',
            name='send_notification_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='اعلام شارژ به کاربر'),
        ),
    ]
