# Generated by Django 5.2 on 2025-05-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_rename_date_income_doc_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomedocument',
            old_name='image',
            new_name='document',
        ),
    ]
