# Generated by Django 5.2 on 2026-01-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_remove_unifiedcharge_base_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedcharge',
            name='charge_by_area_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='charge_by_person_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='fix_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='fix_area_variable_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='fix_person_variable_amount',
            field=models.IntegerField(),
        ),
    ]
