# Generated by Django 5.2 on 2026-02-05 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_announcement_house'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmessagetomiddle',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='adminmessagetomiddle',
            name='user',
        ),
        migrations.AddField(
            model_name='adminmessagetomiddle',
            name='sender',
            field=models.ForeignKey(default=1, limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_admin_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminmessagetomiddle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='adminmessagetomiddle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='adminmessagetomiddle',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='adminmessagetomiddle',
            name='middleAdmins',
            field=models.ManyToManyField(related_name='received_admin_messages', to=settings.AUTH_USER_MODEL, verbose_name='مدیران ساختمان'),
        ),
        migrations.AlterField(
            model_name='adminmessagetomiddle',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='عنوان پیام'),
        ),
        migrations.AlterField(
            model_name='middlemessagereadstatus',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
        migrations.AlterField(
            model_name='middlemessagereadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='admin_panel.adminmessagetomiddle'),
        ),
        migrations.AlterField(
            model_name='middlemessagereadstatus',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن'),
        ),
    ]
