# Generated by Django 5.2 on 2025-12-05 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_rename_payment_penalty_amount_fixedchargecalc_payment_penalty_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('fixed', 'FixedChargeCalc'), ('area', 'AreaChargeCalc'), ('person', 'PersonChargeCalc'), ('fix_person', 'FixPersonChargeCalc'), ('fix_area', 'FixAreaChargeCalc'), ('person_area', 'ChargeByPersonAreaCalc'), ('fix_person_area', 'ChargeByFixPersonAreaCalc'), ('fix_variable', 'ChargeFixVariableCalc')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('send_notification_date', models.DateField(blank=True, null=True, verbose_name='اعلام شارژ به کاربر')),
                ('payment_deadline_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
