# Generated by Django 5.2 on 2025-10-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_alter_areachargecalc_send_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areachargecalc',
            name='send_notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='اعلام شارژ به کاربر'),
        ),
    ]
