# Generated by Django 5.2 on 2025-05-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_rename_image_incomedocument_document'),
        ('user_app', '0016_alter_myhouse_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(max_length=200, verbose_name='پرداخت کننده')),
                ('doc_date', models.DateField(verbose_name='تاریخ سند')),
                ('doc_number', models.IntegerField(verbose_name='شماره سند')),
                ('description', models.CharField(max_length=4000, verbose_name='شرح')),
                ('amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ')),
                ('details', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.myhouse', verbose_name='شماره حساب')),
            ],
        ),
    ]
