# Generated by Django 5.2 on 2026-01-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_alter_unifiedcharge_charge_by_area_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unifiedcharge',
            old_name='amount',
            new_name='base_charge',
        ),
    ]
