# Generated by Django 5.2 on 2026-02-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_remove_adminmessagetomiddle_is_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessagetomiddle',
            name='send_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminmessagetomiddle',
            name='send_notification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
