# Generated by Django 5.2 on 2025-12-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_unifiedcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
    ]
