# Generated by Django 5.2 on 2026-01-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_rename_amount_unifiedcharge_base_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedcharge',
            name='base_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
