# Generated by Django 5.2 on 2025-12-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_unifiedcharge_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='areachargecalc',
            name='payment_penalty_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonareacalc',
            name='payment_penalty_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='chargebypersonareacalc',
            name='payment_penalty_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='chargefixvariablecalc',
            name='payment_penalty_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='fixareachargecalc',
            name='payment_penalty_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='payment_penalty_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='personchargecalc',
            name='payment_penalty_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
