# Generated by Django 5.2 on 2025-05-06 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_receivemoney'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='images/receive/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.receiveMoney')),
            ],
        ),
    ]
