# Generated by Django 5.2 on 2025-10-31 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_smsmanagement'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmanagement',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_unit', to='user_app.unit'),
        ),
    ]
