# Generated by Django 5.2 on 2026-02-07 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_unifiedcharge_house'),
        ('user_app', '0011_user_is_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_expenses', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='income',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_incomes', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_maintenance', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='paymoney',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_payments', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='property',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_property', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AddField(
            model_name='receivemoney',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_receives', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
    ]
