# Generated by Django 5.2 on 2026-01-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_alter_unifiedcharge_base_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='penalty_percent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
