# Generated by Django 5.2 on 2025-05-06 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_receivedocument'),
        ('user_app', '0016_alter_myhouse_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivemoney',
            name='payer_name',
            field=models.CharField(max_length=200, verbose_name='دریافت کننده'),
        ),
        migrations.CreateModel(
            name='PayerMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='پرداخت کننده')),
                ('document_date', models.DateField(verbose_name='تاریخ سند')),
                ('document_number', models.IntegerField(verbose_name='شماره سند')),
                ('description', models.CharField(max_length=4000, verbose_name='شرح')),
                ('amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ')),
                ('details', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.myhouse', verbose_name='شماره حساب')),
            ],
        ),
        migrations.CreateModel(
            name='PayerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='images/payment/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.payermoney')),
            ],
        ),
    ]
