# Generated by Django 5.2 on 2025-12-05 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_areachargecalc_payment_penalty_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personchargecalc',
            name='send_notification_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='اعلام شارژ به کاربر'),
            preserve_default=False,
        ),
    ]
