# Generated by Django 5.2 on 2025-10-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_smsmanagement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsmanagement',
            old_name='is_sent',
            new_name='send_notification',
        ),
        migrations.AddField(
            model_name='smsmanagement',
            name='send_notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='اعلام شارژ به کاربر'),
        ),
    ]
