# Generated by Django 5.2 on 2026-02-07 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_expense_house_income_house_maintenance_house_and_more'),
        ('user_app', '0011_user_is_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmanagement',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_sms', to='user_app.myhouse'),
        ),
    ]
