# Generated by Django 5.2 on 2025-12-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_alter_personchargecalc_send_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personchargecalc',
            name='send_notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='اعلام شارژ به کاربر'),
        ),
    ]
