# Generated by Django 5.2 on 2026-01-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_unifiedcharge_penalty_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixcharge',
            name='total_charge_month',
        ),
        migrations.DeleteModel(
            name='FixedChargeCalc',
        ),
    ]
