# Generated by Django 5.2 on 2025-05-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_alter_receivemoney_payer_name_payermoney_and_more'),
        ('user_app', '0016_alter_myhouse_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedocument',
            name='receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.receivemoney'),
        ),
        migrations.AlterField(
            model_name='receivemoney',
            name='payer_name',
            field=models.CharField(max_length=200, verbose_name='پرداخت کننده'),
        ),
        migrations.CreateModel(
            name='PayMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='دریافت کننده')),
                ('document_date', models.DateField(verbose_name='تاریخ سند')),
                ('document_number', models.IntegerField(verbose_name='شماره سند')),
                ('description', models.CharField(max_length=4000, verbose_name='شرح')),
                ('amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ')),
                ('details', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.myhouse', verbose_name='شماره حساب')),
            ],
        ),
        migrations.AlterField(
            model_name='payerdocument',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.paymoney'),
        ),
        migrations.DeleteModel(
            name='PayerMoney',
        ),
    ]
