# Generated by Django 5.2 on 2026-02-07 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_smsmanagement_house'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSmsManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('send_notification_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_units_sent', models.PositiveIntegerField(default=0)),
                ('sms_per_message', models.PositiveIntegerField(default=0)),
                ('total_sms_sent', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('notified_users', models.ManyToManyField(blank=True, related_name='admin_sms_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_sms_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
