# Generated by Django 5.2 on 2025-05-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_alter_receivedocument_receive_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayerDocument',
            new_name='PayDocument',
        ),
    ]
