# Generated by Django 5.2 on 2025-12-08 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_alter_personchargecalc_send_notification_date'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='unifiedcharge',
            old_name='description',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='related_object_id',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='related_object_type',
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='civil',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='شارژ عمرانی'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='details',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='other_cost_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='penalty_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='total_charge_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='charge_type',
            field=models.CharField(choices=[('fixed', 'Fixed Charge'), ('area', 'Area Charge'), ('person', 'Person Charge'), ('fix_person', 'Fixed Person Charge'), ('fix_area', 'Fixed Area Charge'), ('person_area', 'Person Area Charge'), ('fix_person_area', 'Fixed Person Area'), ('fix_variable', 'Variable Fixed Charge')], max_length=50),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='payment_deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='مهلت پرداخت'),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='send_notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ارسال اعلان'),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_charges', to=settings.AUTH_USER_MODEL),
        ),
    ]
