# Generated by Django 5.2 on 2026-01-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_remove_chargebyfixpersonareacalc_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedcharge',
            name='charge_by_area_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='charge_by_person_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='fix_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='fix_area_variable_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedcharge',
            name='fix_person_variable_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
