# Generated by Django 5.2 on 2025-05-08 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_rename_payerdocument_paydocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=400, verbose_name='نام')),
                ('property_unit', models.CharField(max_length=3000, verbose_name='واحد')),
                ('property_location', models.CharField(max_length=400, verbose_name='آدرس')),
                ('property_code', models.CharField(max_length=200, verbose_name='کد')),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='ارزش')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='images/property/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.property')),
            ],
        ),
    ]
