# Generated by Django 5.2 on 2025-12-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_rename_description_unifiedcharge_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedchargecalc',
            name='base_charge',
            field=models.PositiveIntegerField(default=1, verbose_name='مبلغ'),
            preserve_default=False,
        ),
    ]
