# Generated by Django 5.2 on 2025-05-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_property_propertydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='property',
            name='details',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ خرید'),
        ),
    ]
