# Generated by Django 5.2 on 2025-12-08 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_fixedchargecalc_base_charge'),
        ('user_app', '0012_calendarnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_charges', to='user_app.unit'),
        ),
    ]
