# Generated by Django 5.2 on 2026-01-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_alter_unifiedcharge_charge_by_area_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedcharge',
            name='charge_type',
            field=models.CharField(choices=[('fix', 'ثابت'), ('area', 'متراژی'), ('person', 'نفری'), ('fix_person', 'ثابت + نفر'), ('fix_area', 'ثابت + متراژ'), ('person_area', 'نفر + متراژ'), ('fix_person_area', 'ثابت + نفر + متراژ'), ('fix_variable', 'ثابت و متغیر')], max_length=50),
        ),
    ]
