# Generated by Django 5.2 on 2026-02-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_smscredit_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscredit',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ شارژ'),
        ),
    ]
