# Generated by Django 5.2 on 2025-05-08 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_property_created_at_property_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_description', models.CharField(max_length=1000, verbose_name='')),
                ('maintenance_start_date', models.DateField(verbose_name='')),
                ('maintenance_end_date', models.DateField(verbose_name='')),
                ('maintenance_price', models.PositiveIntegerField(verbose_name='')),
                ('maintenance_status', models.CharField(max_length=100, verbose_name='')),
                ('service_company', models.CharField(max_length=200, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='images/maintenance/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.maintenance')),
            ],
        ),
    ]
