# Generated by Django 5.2 on 2026-01-02 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_alter_unifiedcharge_charge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='fix_base_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_charges', to='admin_panel.fixcharge'),
        ),
    ]
