# Generated by Django 5.2 on 2025-12-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_unifiedcharge_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='areachargecalc',
            name='base_charge',
            field=models.PositiveIntegerField(default=1, verbose_name='مبلغ'),
            preserve_default=False,
        ),
    ]
