# Generated by Django 5.2 on 2025-05-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_maintenance_maintenancedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='details',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name=''),
        ),
    ]
