# Generated by Django 5.2 on 2025-12-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_areachargecalc_base_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
