# Generated by Django 5.2 on 2025-12-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_unifiedcharge_transaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebyfixpersonareacalc',
            name='base_charge',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ'),
        ),
        migrations.AddField(
            model_name='chargebypersonareacalc',
            name='base_charge',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ'),
        ),
        migrations.AddField(
            model_name='chargefixvariablecalc',
            name='base_charge',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ'),
        ),
        migrations.AddField(
            model_name='fixareachargecalc',
            name='base_charge',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ'),
        ),
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='base_charge',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ'),
        ),
        migrations.AddField(
            model_name='personchargecalc',
            name='base_charge',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='areachargecalc',
            name='base_charge',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='fixedchargecalc',
            name='base_charge',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ'),
        ),
    ]
