# Generated by Django 5.2 on 2026-01-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_remove_fixcharge_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='charge_by_area_amount',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='charge_by_person_amount',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='fix_amount',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='fix_area_variable_amount',
        ),
        migrations.RemoveField(
            model_name='unifiedcharge',
            name='fix_person_variable_amount',
        ),
    ]
