# Generated by Django 5.2 on 2025-05-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_maintenance_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_document_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=''),
        ),
    ]
