# Generated by Django 5.2 on 2025-12-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_chargebyfixpersonareacalc_base_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='send_notification',
            field=models.BooleanField(default=False),
        ),
    ]
