# Generated by Django 5.2 on 2026-01-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_remove_unifiedcharge_charge_by_area_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
