# Generated by Django 5.2 on 2025-05-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_maintenance_maintenance_document_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_price',
            field=models.PositiveIntegerField(verbose_name='ارزش'),
        ),
    ]
