# Generated by Django 5.2 on 2025-12-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_unifiedcharge_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
