# Generated by Django 5.2 on 2026-01-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_unifiedcharge_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargebyfixpersonarea',
            name='area_amount',
        ),
        migrations.RemoveField(
            model_name='chargebyfixpersonarea',
            name='person_amount',
        ),
        migrations.RemoveField(
            model_name='fixareacharge',
            name='area_amount',
        ),
        migrations.RemoveField(
            model_name='fixpersoncharge',
            name='person_amount',
        ),
        migrations.AddField(
            model_name='chargebyfixpersonarea',
            name='charge_area_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ به ازای هر متر'),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonarea',
            name='charge_person_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ به ازای هر نفر'),
        ),
        migrations.AddField(
            model_name='fixareacharge',
            name='fix_area_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ به ازای هر متر'),
        ),
        migrations.AddField(
            model_name='fixpersoncharge',
            name='fix_person_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ به ازای هر نفر'),
        ),
        migrations.AlterField(
            model_name='areacharge',
            name='area_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ به ازای هر متر'),
        ),
        migrations.AlterField(
            model_name='chargebyfixpersonarea',
            name='fix_charge_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ به ازای هر واحد'),
        ),
        migrations.AlterField(
            model_name='chargebypersonarea',
            name='area_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ به ازای هر متر'),
        ),
        migrations.AlterField(
            model_name='chargebypersonarea',
            name='person_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ به ازای هر نفر'),
        ),
        migrations.AlterField(
            model_name='chargefixvariable',
            name='extra_parking_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ هزینه پارکینگ اضافه'),
        ),
        migrations.AlterField(
            model_name='chargefixvariable',
            name='unit_fix_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ ثابت به ازای هر واحد'),
        ),
        migrations.AlterField(
            model_name='chargefixvariable',
            name='unit_variable_area_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ متغیر به ازای هر متر'),
        ),
        migrations.AlterField(
            model_name='chargefixvariable',
            name='unit_variable_person_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ متغیر به ازای هر نفر'),
        ),
        migrations.AlterField(
            model_name='fixareacharge',
            name='fix_charge_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ به ازای هر واحد'),
        ),
        migrations.AlterField(
            model_name='fixcharge',
            name='fix_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ به ازای هر واحد'),
        ),
        migrations.AlterField(
            model_name='fixpersoncharge',
            name='fix_charge_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ به ازای هر واحد'),
        ),
        migrations.AlterField(
            model_name='personcharge',
            name='person_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ به ازای هر نفر'),
        ),
    ]
