# Generated by Django 5.2 on 2025-05-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_alter_property_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_price',
            field=models.IntegerField(verbose_name='ارزش'),
        ),
    ]
