# Generated by Django 5.2 on 2026-02-16 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_alter_fund_unit_alter_fund_user'),
        ('user_app', '0017_alter_unitresidencehistory_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_count', models.PositiveIntegerField(verbose_name='تعداد واحد')),
                ('price_per_unit_month', models.PositiveIntegerField(verbose_name='هزینه هر واحد در ماه')),
                ('duration', models.PositiveSmallIntegerField(choices=[(3, 'سه\u200cماهه'), (6, 'شش\u200cماهه'), (12, 'دوازده\u200cماهه')], verbose_name='مدت اشتراک (ماه)')),
                ('total_amount', models.PositiveIntegerField(verbose_name='مبلغ کل')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('transaction_no', models.CharField(blank=True, max_length=150, null=True, verbose_name='شماره تراکنش')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال است؟')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='user_app.myhouse', verbose_name='ساختمان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
