# Generated by Django 5.2 on 2025-05-10 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_alter_property_property_price'),
        ('user_app', '0016_alter_myhouse_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeByPersonArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_month', models.CharField(max_length=100, verbose_name='نام شارژ')),
                ('person_charge', models.PositiveIntegerField(verbose_name='شارژ به ازای نفرات')),
                ('area_charge', models.PositiveIntegerField(verbose_name='شارژ به ازای متراژ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_by_person_area', to='user_app.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_by_person_area', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeCalcFixVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_month', models.CharField(max_length=100, verbose_name='نام شارژ')),
                ('salary', models.PositiveIntegerField(verbose_name='هزینه حقوق و دستمزد')),
                ('elevator_fix_cost', models.PositiveIntegerField(verbose_name='هزینه 60% آسانسور')),
                ('public_electricity', models.PositiveIntegerField(verbose_name='هزینه برق عمومی')),
                ('common_expenses', models.PositiveIntegerField(verbose_name='هزینه های سالیانه عمومی(روشنایی،نظافت و ...)')),
                ('facility_cost', models.PositiveIntegerField(verbose_name='هزینه سالیانه تاسیسات')),
                ('extinguished_cost', models.PositiveIntegerField(verbose_name='هزینه سالیانه آتش نشانس')),
                ('camera_cost', models.PositiveIntegerField(verbose_name='هزینه سالیانه دوربین')),
                ('insurance_cost', models.PositiveIntegerField(verbose_name='هزینه سالیانه بیمه')),
                ('office_cost', models.PositiveIntegerField(verbose_name='هزینه اداری و دفتری')),
                ('green_space_cost', models.PositiveIntegerField(verbose_name='هزینه فضای سبز')),
                ('elevator_variable_cost', models.PositiveIntegerField(verbose_name='هزینه 40% آسانسور')),
                ('public_water', models.PositiveIntegerField(verbose_name='هزینه آب مشاع')),
                ('public_gas', models.PositiveIntegerField(verbose_name='هزینه گاز مشاع')),
                ('civil_charge_cost', models.PositiveIntegerField(verbose_name='هزینه عمرانی')),
                ('payment_deadline', models.DateField(verbose_name='مهلت پرداخت')),
                ('surcharge', models.PositiveIntegerField(verbose_name='جریمه عدم پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_calc_fix', to='user_app.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_calc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FixedChargeCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_fix', to='user_app.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_fix', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
