# Generated by Django 5.2 on 2026-02-16 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_subscription'),
        ('user_app', '0017_alter_unitresidencehistory_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(choices=[(3, 'سه ماهه'), (6, 'شش ماهه'), (12, 'دوازده ماهه')], unique=True, verbose_name='مدت اشتراک')),
                ('price_per_unit', models.PositiveIntegerField(verbose_name='هزینه هر واحد برای این پلن')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price_per_unit_month',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='transaction_no',
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.myhouse'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subscriptionplan', verbose_name='پلن اشتراک'),
            preserve_default=False,
        ),
    ]
