# Generated by Django 5.2 on 2026-01-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_remove_chargebyfixpersonarea_area_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargebyfixpersonarea',
            old_name='charge_area_amount',
            new_name='area_amount',
        ),
        migrations.RenameField(
            model_name='chargebyfixpersonarea',
            old_name='charge_person_amount',
            new_name='person_amount',
        ),
        migrations.RenameField(
            model_name='fixareacharge',
            old_name='fix_area_amount',
            new_name='area_amount',
        ),
        migrations.RenameField(
            model_name='fixpersoncharge',
            old_name='fix_person_amount',
            new_name='person_amount',
        ),
    ]
