# Generated by Django 5.2 on 2025-05-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_chargebypersonarea_chargecalcfixvariable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedchargecalc',
            name='charge_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان شارژ'),
        ),
    ]
