# Generated by Django 5.2 on 2026-01-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_rename_charge_area_amount_chargebyfixpersonarea_area_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='extra_parking_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
