# Generated by Django 5.2 on 2025-12-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_messagetouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetouser',
            name='message',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
