# Generated by Django 5.2 on 2025-05-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_fixedchargecalc_charge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedchargecalc',
            name='details',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name=''),
        ),
    ]
