# Generated by Django 5.2 on 2025-12-13 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_alter_messagetouser_message'),
        ('user_app', '0012_calendarnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetouser',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_unit', to='user_app.unit'),
        ),
    ]
