# Generated by Django 5.2 on 2025-05-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_fixedchargecalc_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedchargecalc',
            name='civil_charge',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ عمرانی'),
        ),
    ]
