# Generated by Django 5.2 on 2026-01-05 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_penalty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='is_penalty_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='penalty_waived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='penalty_waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_penalties', to=settings.AUTH_USER_MODEL),
        ),
    ]
