# Generated by Django 5.2 on 2025-12-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_messagetouser_unit'),
        ('user_app', '0012_calendarnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetouser',
            name='unit',
        ),
        migrations.AddField(
            model_name='messagetouser',
            name='units',
            field=models.ManyToManyField(related_name='messages', to='user_app.unit', verbose_name='واحدها'),
        ),
    ]
