# Generated by Django 5.2 on 2025-05-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_fixedchargecalc_civil_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedchargecalc',
            name='total_charge_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ کل ماهانه'),
        ),
    ]
