# Generated by Django 5.2 on 2026-01-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_unifiedcharge_is_penalty_waived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='previous_penalty_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
