# Generated by Django 5.2 on 2026-02-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_subscriptionplan_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.PositiveSmallIntegerField(choices=[(3, 'سه ماهه'), (6, 'شش ماهه'), (12, 'دوازده ماهه')], verbose_name='مدت اشتراک'),
        ),
    ]
