# Generated by Django 5.2 on 2026-02-17 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_alter_subscriptionplan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subscriptionplan', verbose_name='پلن اشتراک'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ کل'),
        ),
    ]
