# Generated by Django 5.2 on 2025-12-18 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_messagereadstatus'),
        ('user_app', '0012_calendarnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
            preserve_default=False,
        ),
    ]
