# Generated by Django 5.2 on 2025-05-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_fixedchargecalc_total_charge_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargebypersonarea',
            name='charge_month',
            field=models.CharField(max_length=100, verbose_name='عنوان شارژ'),
        ),
    ]
