# Generated by Django 5.2 on 2026-01-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_unifiedcharge_previous_penalty_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
