# Generated by Django 5.2 on 2025-05-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_alter_chargebypersonarea_charge_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebypersonarea',
            name='details',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='chargebypersonarea',
            name='total_charge_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ کل ماهانه'),
        ),
        migrations.AlterField(
            model_name='chargebypersonarea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='chargebypersonarea',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
    ]
