# Generated by Django 5.2 on 2026-02-17 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_subscription_is_trial_subscription_trial_end_and_more'),
        ('user_app', '0017_alter_unitresidencehistory_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.myhouse'),
        ),
    ]
