# Generated by Django 5.2 on 2025-12-18 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_expense_bank_income_bank'),
        ('user_app', '0012_calendarnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
            preserve_default=False,
        ),
    ]
