# Generated by Django 5.2 on 2026-01-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_delete_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده/ نشده'),
        ),
    ]
