# Generated by Django 5.2 on 2026-02-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_alter_subscription_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='trial_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='trial_start',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='end_date',
            new_name='trial_end',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='start_date',
            new_name='trial_start',
        ),
    ]
