# Generated by Django 5.2 on 2025-12-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_fund_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='final_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
