# Generated by Django 5.2 on 2025-05-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_chargebypersonarea_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebypersonarea',
            name='civil_charge',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ عمرانی'),
        ),
    ]
