# Generated by Django 5.2 on 2026-01-06 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_expense_is_paid'),
        ('user_app', '0002_myhouse_floor_counts_myhouse_unit_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='income',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
    ]
