# Generated by Django 5.2 on 2025-12-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_alter_fund_final_amount'),
        ('user_app', '0013_bank_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_charges', to='user_app.bank'),
        ),
    ]
