# Generated by Django 5.2 on 2026-01-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_alter_expense_bank_alter_income_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
