# Generated by Django 5.2 on 2026-02-19 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_rename_trial_end_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='trial_end',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='trial_start',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
