# Generated by Django 5.2 on 2025-05-11 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_chargebypersonarea_civil_charge'),
        ('user_app', '0017_rename_people_count_unit_renter_people_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaChargeCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان شارژ')),
                ('area_amount', models.PositiveIntegerField(verbose_name='مبلغ')),
                ('civil_charge', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ عمرانی')),
                ('total_charge_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ کل ماهانه')),
                ('details', models.CharField(blank=True, max_length=4000, null=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_area', to='user_app.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_area', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonChargeCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان شارژ')),
                ('person_amount', models.PositiveIntegerField(verbose_name='مبلغ')),
                ('civil_charge', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ عمرانی')),
                ('total_charge_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ کل ماهانه')),
                ('details', models.CharField(blank=True, max_length=4000, null=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_person', to='user_app.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
