# Generated by Django 5.2 on 2026-01-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_expense_payment_date_expense_payment_gateway_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payment_gateway',
        ),
    ]
