# Generated by Django 5.2 on 2025-05-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_areachargecalc_personchargecalc'),
    ]

    operations = [
        migrations.AddField(
            model_name='areachargecalc',
            name='final_area_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ نهایی'),
        ),
        migrations.AddField(
            model_name='personchargecalc',
            name='final_person_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ نهایی'),
        ),
    ]
