# Generated by Django 5.2 on 2025-12-19 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_unifiedcharge_bank'),
        ('user_app', '0013_bank_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivemoney',
            name='payer_name',
        ),
        migrations.AddField(
            model_name='fund',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
        migrations.AddField(
            model_name='receivemoney',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
    ]
