# Generated by Django 5.2 on 2025-12-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0035_remove_receivemoney_payer_name_fund_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='prayer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receivemoney',
            name='payer_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
