# Generated by Django 5.2 on 2025-05-13 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0035_areachargecalc_final_area_amount_and_more'),
        ('user_app', '0024_unit_people_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixAreaChargeCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان شارژ')),
                ('fix_charge', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ ثابت')),
                ('Area_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ به ازای متراژ')),
                ('final_person_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ نهایی')),
                ('civil_charge', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ عمرانی')),
                ('total_charge_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ کل ماهانه')),
                ('details', models.CharField(blank=True, max_length=4000, null=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_fix_area', to='user_app.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_fix_area', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FixPersonChargeCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان شارژ')),
                ('fix_charge', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ ثابت')),
                ('person_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ به ازای نفرات')),
                ('final_person_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ نهایی')),
                ('civil_charge', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ عمرانی')),
                ('total_charge_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ کل ماهانه')),
                ('details', models.CharField(blank=True, max_length=4000, null=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_fix_person', to='user_app.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_fix_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
