# Generated by Django 5.2 on 2026-01-07 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0035_remove_expense_payment_gateway'),
        ('user_app', '0002_myhouse_floor_counts_myhouse_unit_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
    ]
