# Generated by Django 5.2 on 2026-02-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0036_alter_subscription_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده')], default='active', max_length=20),
        ),
    ]
