# Generated by Django 5.2 on 2026-01-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0036_expense_receiver_name_expense_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده/ نشده'),
        ),
        migrations.AddField(
            model_name='income',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='income',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
