# Generated by Django 5.2 on 2025-12-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0036_fund_prayer_name_fund_receiver_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='prayer_name',
            new_name='payer_name',
        ),
    ]
