# Generated by Django 5.2 on 2025-05-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0036_fixareachargecalc_fixpersonchargecalc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixareachargecalc',
            old_name='Area_amount',
            new_name='area_amount',
        ),
    ]
