# Generated by Django 5.2 on 2026-04-17 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0037_remove_subscription_is_active_subscription_status'),
        ('user_app', '0023_rename_phone_number_myhouse_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='bank',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده/ نشده'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='receiver_name',
            field=models.CharField(default=113, max_length=200, verbose_name='دریافت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='transaction_reference',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bank',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده/ نشده'),
        ),
        migrations.AddField(
            model_name='property',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='property',
            name='receiver_name',
            field=models.CharField(default=20, max_length=200, verbose_name='دریافت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='transaction_reference',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
