# Generated by Django 5.2 on 2026-01-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0037_income_is_paid_income_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivemoney',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده/ نشده'),
        ),
        migrations.AddField(
            model_name='receivemoney',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='receivemoney',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
