# Generated by Django 5.2 on 2025-05-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0037_rename_area_amount_fixareachargecalc_area_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areachargecalc',
            old_name='final_area_amount',
            new_name='final_fix_area_amount',
        ),
    ]
