# Generated by Django 5.2 on 2025-12-19 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0037_rename_prayer_name_fund_payer_name'),
        ('user_app', '0013_bank_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymoney',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
    ]
