# Generated by Django 5.2 on 2026-01-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0038_receivemoney_is_paid_receivemoney_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivemoney',
            name='is_received',
        ),
    ]
