# Generated by Django 5.2 on 2025-12-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0038_paymoney_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='is_initial',
            field=models.BooleanField(default=False, verbose_name='افتتاحیه حساب'),
        ),
    ]
