# Generated by Django 5.2 on 2026-04-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0038_maintenance_bank_maintenance_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='document_number',
            field=models.IntegerField(default=1, verbose_name='شماره سند'),
            preserve_default=False,
        ),
    ]
