# Generated by Django 5.2 on 2025-12-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0039_fund_is_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
