# Generated by Django 5.2 on 2026-04-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0039_property_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
            preserve_default=False,
        ),
    ]
