# Generated by Django 5.2 on 2025-05-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0039_rename_final_fix_area_amount_areachargecalc_final_area_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='personchargecalc',
            name='total_charge_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ کل سالیانه'),
        ),
    ]
