# Generated by Django 5.2 on 2025-05-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0040_personchargecalc_total_charge_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='personchargecalc',
            name='total_people',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد نفرات'),
        ),
        migrations.AddField(
            model_name='personchargecalc',
            name='unit_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد واحدها'),
        ),
    ]
