# Generated by Django 5.2 on 2025-12-25 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0040_alter_fund_payment_date'),
        ('user_app', '0022_unitresidencehistory_delete_unitownerhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='payer_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
    ]
