# Generated by Django 5.2 on 2026-04-25 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0040_property_count'),
        ('user_app', '0023_rename_phone_number_myhouse_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('amount', models.PositiveIntegerField(verbose_name='')),
                ('prepayment', models.PositiveIntegerField(verbose_name='')),
                ('installment_count', models.PositiveIntegerField(verbose_name='')),
                ('first_due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع اقساط')),
                ('details', models.TextField()),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده/ نشده')),
                ('transaction_reference', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_civil', to='user_app.myhouse', verbose_name='ساختمان مرتبط')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CivilInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('civil_manage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='admin_panel.civilmanage')),
            ],
        ),
    ]
