# Generated by Django 5.2 on 2025-12-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0041_income_payer_name_income_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fund',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymoney',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='receivemoney',
            name='is_received',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
