# Generated by Django 5.2 on 2025-05-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0041_personchargecalc_total_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedchargecalc',
            name='unit_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد واحدها'),
        ),
    ]
