# Generated by Django 5.2 on 2026-04-25 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0041_civilmanage_civilinstallment'),
        ('user_app', '0023_rename_phone_number_myhouse_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilmanage',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='civilmanage',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='civilmanage',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='civilmanage',
            name='transaction_reference',
        ),
        migrations.RemoveField(
            model_name='civilmanage',
            name='unit',
        ),
        migrations.AddField(
            model_name='civilinstallment',
            name='bank',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='civilinstallment',
            name='transaction_reference',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='civilinstallment',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit'),
        ),
        migrations.AlterField(
            model_name='civilinstallment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده/ نشده'),
        ),
        migrations.AlterField(
            model_name='civilinstallment',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
