# Generated by Django 5.2 on 2025-05-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0042_fixedchargecalc_unit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='areachargecalc',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ کل'),
        ),
        migrations.AddField(
            model_name='areachargecalc',
            name='unit_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد واحدها'),
        ),
    ]
