# Generated by Django 5.2 on 2026-04-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0042_remove_civilmanage_bank_remove_civilmanage_is_paid_and_more'),
        ('user_app', '0023_rename_phone_number_myhouse_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilinstallment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
    ]
