# Generated by Django 5.2 on 2025-05-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0043_areachargecalc_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areachargecalc',
            old_name='total_amount',
            new_name='total_area',
        ),
    ]
