# Generated by Django 5.2 on 2026-04-26 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0043_alter_civilinstallment_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='images/civil/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_documents', to='admin_panel.civilmanage')),
            ],
        ),
    ]
