# Generated by Django 5.2 on 2026-04-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0044_civildocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilinstallment',
            name='send_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilinstallment',
            name='send_notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ارسال اعلان'),
        ),
    ]
