# Generated by Django 5.2 on 2025-05-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0044_rename_total_amount_areachargecalc_total_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixareachargecalc',
            name='total_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ کل'),
        ),
        migrations.AddField(
            model_name='fixareachargecalc',
            name='unit_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد واحدها'),
        ),
    ]
