# Generated by Django 5.2 on 2026-04-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0045_civilinstallment_send_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilinstallment',
            name='prepayment_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
