# Generated by Django 5.2 on 2025-05-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0045_fixareachargecalc_total_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='total_people',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد نفرات'),
        ),
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='unit_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد واحدها'),
        ),
    ]
