# Generated by Django 5.2 on 2026-04-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0046_civilinstallment_prepayment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='civilinstallment',
            old_name='prepayment_amount',
            new_name='prepayment_per_unit',
        ),
    ]
