# Generated by Django 5.2 on 2025-05-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0046_fixpersonchargecalc_total_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebypersonarea',
            name='total_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ کل'),
        ),
        migrations.AddField(
            model_name='chargebypersonarea',
            name='total_people',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=' کل نفرات'),
        ),
        migrations.AddField(
            model_name='chargebypersonarea',
            name='unit_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد واحدها'),
        ),
    ]
