# Generated by Django 5.2 on 2025-05-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0047_chargebypersonarea_total_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargebypersonarea',
            name='charge_month',
        ),
        migrations.AddField(
            model_name='chargebypersonarea',
            name='charge_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان شارژ'),
        ),
    ]
