# Generated by Django 5.2 on 2026-04-29 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0047_rename_prepayment_amount_civilinstallment_prepayment_per_unit'),
        ('user_app', '0023_rename_phone_number_myhouse_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilinstallment',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_installment', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
    ]
