# Generated by Django 5.2 on 2026-05-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0048_civilinstallment_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilinstallment',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
