# Generated by Django 5.2 on 2025-05-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0048_remove_chargebypersonarea_charge_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebypersonarea',
            name='final_person_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ نهایی'),
        ),
    ]
