# Generated by Django 5.2 on 2025-05-15 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0049_chargebypersonarea_final_person_amount'),
        ('user_app', '0024_unit_people_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeByFixPersonArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان شارژ')),
                ('fix_charge', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ ثابت')),
                ('person_charge', models.PositiveIntegerField(verbose_name='شارژ به ازای نفرات')),
                ('area_charge', models.PositiveIntegerField(verbose_name='شارژ به ازای متراژ')),
                ('unit_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد واحدها')),
                ('total_people', models.PositiveIntegerField(blank=True, null=True, verbose_name=' کل نفرات')),
                ('total_area', models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ کل')),
                ('final_person_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ نهایی')),
                ('total_charge_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ کل ماهانه')),
                ('details', models.CharField(blank=True, max_length=4000, null=True, verbose_name='')),
                ('civil_charge', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ عمرانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_by_fix_person_area', to='user_app.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_by_fix_person_area', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
