# Generated by Django 5.2 on 2025-05-15 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0050_chargebyfixpersonarea'),
        ('user_app', '0024_unit_people_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargecalcfixvariable',
            name='charge_month',
        ),
        migrations.RemoveField(
            model_name='chargecalcfixvariable',
            name='payment_deadline',
        ),
        migrations.RemoveField(
            model_name='chargecalcfixvariable',
            name='surcharge',
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='charge_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شارژ'),
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_charge', to='admin_panel.expense'),
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='final_person_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ نهایی'),
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='fix_charge',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ ثابت'),
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='total_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ کل'),
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='total_charge_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ کل ماهانه'),
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='total_people',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=' کل نفرات'),
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='unit_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد واحدها'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='camera_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه سالیانه دوربین'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='civil_charge_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه عمرانی'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='common_expenses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه های سالیانه عمومی(روشنایی،نظافت و ...)'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='elevator_fix_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه 60% آسانسور'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='elevator_variable_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه 40% آسانسور'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='extinguished_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه سالیانه آتش نشانس'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='facility_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه سالیانه تاسیسات'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='green_space_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه فضای سبز'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='insurance_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه سالیانه بیمه'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='office_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه اداری و دفتری'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='public_electricity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه برق عمومی'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='public_gas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه گاز مشاع'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='public_water',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه آب مشاع'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه حقوق و دستمزد'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_calc_fix', to='user_app.unit'),
        ),
        migrations.AlterField(
            model_name='chargecalcfixvariable',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_calc', to=settings.AUTH_USER_MODEL),
        ),
    ]
