# Generated by Django 5.2 on 2026-05-08 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0050_sewagemanage_sewageinstallment_sewagedocument'),
        ('user_app', '0024_bank_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankfund',
            name='to_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='user_app.bank'),
        ),
        migrations.AddField(
            model_name='bankfund',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('transfer', 'انتقال')], default='deposit', max_length=20),
        ),
    ]
