# Generated by Django 5.2 on 2026-05-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0051_bankfund_to_bank_bankfund_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankfund',
            name='balance_after',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
