# Generated by Django 5.2 on 2025-05-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0051_remove_chargecalcfixvariable_charge_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargecalcfixvariable',
            old_name='civil_charge_cost',
            new_name='civil_charge',
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='details',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name=''),
        ),
    ]
