# Generated by Django 5.2 on 2026-05-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0052_bankfund_balance_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankfund',
            name='payer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bankfund',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
