# Generated by Django 5.2 on 2025-05-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0052_rename_civil_charge_cost_chargecalcfixvariable_civil_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargecalcfixvariable',
            name='final_person_amount',
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='unit_fix_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ ثابت'),
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='unit_variable_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ متغیر'),
        ),
    ]
