# Generated by Django 5.2 on 2025-05-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0053_remove_chargecalcfixvariable_final_person_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='elevator_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه  آسانسور'),
        ),
    ]
