# Generated by Django 5.2 on 2026-05-09 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0053_bankfund_payer_name_bankfund_receiver_name'),
        ('user_app', '0024_bank_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankfund',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks_funds', to='user_app.unit'),
        ),
    ]
