# Generated by Django 5.2 on 2025-05-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0054_chargecalcfixvariable_elevator_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargecalcfixvariable',
            name='unit_variable_amount',
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='unit_variable_amount_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ متغیر هر متر'),
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='unit_variable_amount_person',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ متغیر هر نفر'),
        ),
    ]
