# Generated by Django 5.2 on 2025-05-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0055_remove_chargecalcfixvariable_unit_variable_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedchargecalc',
            name='send_notification',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='اعلام شارژ به کاربر'),
        ),
    ]
