# Generated by Django 5.2 on 2026-05-11 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0055_alter_receivemoney_bank'),
        ('user_app', '0024_bank_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymoney',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
    ]
