# Generated by Django 5.2 on 2025-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0056_fixedchargecalc_send_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedchargecalc',
            name='send_notification',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر'),
        ),
    ]
