# Generated by Django 5.2 on 2025-05-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0057_alter_fixedchargecalc_send_notification'),
        ('user_app', '0027_alter_unit_owner_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='')),
                ('fix_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ')),
                ('civil', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ عمرانی')),
                ('details', models.CharField(blank=True, max_length=4000, null=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_charge', to='user_app.unit')),
            ],
        ),
        migrations.AddField(
            model_name='fixedchargecalc',
            name='fix_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fix_charge_amount', to='admin_panel.fixcharge'),
            preserve_default=False,
        ),
    ]
