# Generated by Django 5.2 on 2026-05-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0057_alter_property_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='فروشنده'),
        ),
    ]
