# Generated by Django 5.2 on 2025-05-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0058_fixcharge_fixedchargecalc_fix_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixcharge',
            name='unit',
        ),
    ]
