# Generated by Django 5.2 on 2026-05-16 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0058_property_company_name'),
        ('user_app', '0024_bank_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
    ]
