# Generated by Django 5.2 on 2025-05-19 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0060_fixedchargecalc_is_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='')),
                ('area_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ')),
                ('civil', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ عمرانی')),
                ('details', models.CharField(blank=True, max_length=4000, null=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.RenameField(
            model_name='areachargecalc',
            old_name='area_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='areachargecalc',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='areachargecalc',
            name='send_notification',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر'),
        ),
        migrations.AddField(
            model_name='areachargecalc',
            name='area_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='area_charge_amount', to='admin_panel.areacharge'),
            preserve_default=False,
        ),
    ]
