# Generated by Django 5.2 on 2026-05-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0060_property_expert_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='expert_name',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='expert_name',
            field=models.CharField(default=1, max_length=200, verbose_name='نام کارشناس'),
            preserve_default=False,
        ),
    ]
