# Generated by Django 5.2 on 2026-05-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0061_remove_property_expert_name_maintenance_expert_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankfund',
            name='transfer_group_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
