# Generated by Django 5.2 on 2025-05-20 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0061_areacharge_rename_area_amount_areachargecalc_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='')),
                ('person_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ')),
                ('civil', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ عمرانی')),
                ('details', models.CharField(blank=True, max_length=4000, null=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.RenameField(
            model_name='personchargecalc',
            old_name='person_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='personchargecalc',
            name='person_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_charge_amount', to='admin_panel.personcharge'),
            preserve_default=False,
        ),
    ]
