# Generated by Django 5.2 on 2025-05-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0062_personcharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebyfixpersonarea',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonarea',
            name='send_notification',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر'),
        ),
        migrations.AddField(
            model_name='chargebypersonarea',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='chargebypersonarea',
            name='send_notification',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر'),
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='send_notification',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر'),
        ),
        migrations.AddField(
            model_name='fixareachargecalc',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='fixareachargecalc',
            name='send_notification',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر'),
        ),
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='send_notification',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر'),
        ),
        migrations.AddField(
            model_name='personchargecalc',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='personchargecalc',
            name='send_notification',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر'),
        ),
    ]
