# Generated by Django 5.2 on 2026-05-23 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0062_bankfund_transfer_group_id'),
        ('user_app', '0024_bank_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminfund',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_houses', to='user_app.myhouse', verbose_name='شماره حساب'),
        ),
    ]
