# Generated by Django 5.2 on 2025-05-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0063_chargebyfixpersonarea_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedchargecalc',
            name='payment_date',
            field=models.DateField(auto_now=True, verbose_name=''),
        ),
    ]
