# Generated by Django 5.2 on 2025-05-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0064_fixedchargecalc_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedchargecalc',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
    ]
