# Generated by Django 5.2 on 2025-05-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0065_alter_fixedchargecalc_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedchargecalc',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر با پیامک'),
        ),
    ]
