# Generated by Django 5.2 on 2025-05-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0066_fixedchargecalc_send_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areachargecalc',
            name='final_area_amount',
        ),
        migrations.AlterField(
            model_name='areachargecalc',
            name='total_charge_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ کل ماهانه هر واحد'),
        ),
    ]
