# Generated by Django 5.2 on 2025-05-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0067_remove_areachargecalc_final_area_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areachargecalc',
            name='final_area_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ نهایی'),
        ),
    ]
