# Generated by Django 5.2 on 2025-05-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0068_areachargecalc_final_area_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcharge',
            name='civil',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='شارژ عمرانی'),
        ),
    ]
