# Generated by Django 5.2 on 2025-05-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0069_alter_personcharge_civil'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixPersonCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='')),
                ('fix_charge_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ ثابت')),
                ('person_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ')),
                ('civil', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='شارژ عمرانی')),
                ('details', models.CharField(blank=True, max_length=4000, null=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
    ]
