# Generated by Django 5.2 on 2025-05-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0070_fixpersoncharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixpersonchargecalc',
            old_name='person_amount',
            new_name='amount',
        ),
    ]
