# Generated by Django 5.2 on 2025-05-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0071_rename_person_amount_fixpersonchargecalc_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='fix_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fix_person', to='admin_panel.fixpersoncharge'),
            preserve_default=False,
        ),
    ]
