# Generated by Django 5.2 on 2025-05-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0072_fixpersonchargecalc_fix_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixpersoncharge',
            name='total_people',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
