# Generated by Django 5.2 on 2025-05-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0073_fixpersoncharge_total_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcharge',
            name='total_people',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
