# Generated by Django 5.2 on 2025-05-28 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0074_personcharge_total_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixpersonchargecalc',
            name='fix_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_person_charge', to='admin_panel.fixpersoncharge'),
        ),
    ]
