# Generated by Django 5.2 on 2025-05-29 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0075_alter_fixpersonchargecalc_fix_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixAreaCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='')),
                ('fix_charge_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ ثابت')),
                ('area_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ')),
                ('total_people', models.PositiveIntegerField(blank=True, null=True)),
                ('civil', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='شارژ عمرانی')),
                ('details', models.CharField(blank=True, max_length=4000, null=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.RenameField(
            model_name='fixareachargecalc',
            old_name='area_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='fixareachargecalc',
            name='fix_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fix_area_charge', to='admin_panel.fixareacharge'),
            preserve_default=False,
        ),
    ]
