# Generated by Django 5.2 on 2025-05-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0076_fixareacharge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixareacharge',
            old_name='total_people',
            new_name='total_area',
        ),
    ]
