# Generated by Django 5.2 on 2025-05-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0077_rename_total_people_fixareacharge_total_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='areachargecalc',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonarea',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='chargebypersonarea',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='fixareachargecalc',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='personchargecalc',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
    ]
