# Generated by Django 5.2 on 2025-05-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0078_areachargecalc_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='paid_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ ثبت\u200cشده برای پرداخت'),
        ),
    ]
