# Generated by Django 5.2 on 2025-05-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0079_fixpersonchargecalc_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixpersonchargecalc',
            name='paid_amount',
        ),
    ]
