# Generated by Django 5.2 on 2025-05-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0080_remove_fixpersonchargecalc_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='areachargecalc',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonarea',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chargebypersonarea',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chargecalcfixvariable',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fixareachargecalc',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fixedchargecalc',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personchargecalc',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
