# Generated by Django 5.2 on 2025-05-30 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0081_areachargecalc_transaction_reference_and_more'),
        ('user_app', '0027_alter_unit_owner_mobile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargebypersonarea',
            name='area_charge',
        ),
        migrations.RemoveField(
            model_name='chargebypersonarea',
            name='charge_name',
        ),
        migrations.RemoveField(
            model_name='chargebypersonarea',
            name='civil_charge',
        ),
        migrations.RemoveField(
            model_name='chargebypersonarea',
            name='final_person_amount',
        ),
        migrations.RemoveField(
            model_name='chargebypersonarea',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='chargebypersonarea',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='chargebypersonarea',
            name='person_charge',
        ),
        migrations.RemoveField(
            model_name='chargebypersonarea',
            name='send_notification',
        ),
        migrations.RemoveField(
            model_name='chargebypersonarea',
            name='total_charge_month',
        ),
        migrations.RemoveField(
            model_name='chargebypersonarea',
            name='transaction_reference',
        ),
        migrations.RemoveField(
            model_name='chargebypersonarea',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='chargebypersonarea',
            name='unit_count',
        ),
        migrations.RemoveField(
            model_name='chargebypersonarea',
            name='user',
        ),
        migrations.AddField(
            model_name='chargebypersonarea',
            name='area_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ'),
        ),
        migrations.AddField(
            model_name='chargebypersonarea',
            name='civil',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='شارژ عمرانی'),
        ),
        migrations.AddField(
            model_name='chargebypersonarea',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='chargebypersonarea',
            name='person_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='chargebypersonarea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='chargebypersonarea',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='chargebypersonarea',
            name='total_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chargebypersonarea',
            name='total_people',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChargeByPersonAreaCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان شارژ')),
                ('person_charge', models.PositiveIntegerField(verbose_name='شارژ به ازای نفرات')),
                ('area_charge', models.PositiveIntegerField(verbose_name='شارژ به ازای متراژ')),
                ('unit_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد واحدها')),
                ('total_people', models.PositiveIntegerField(blank=True, null=True, verbose_name=' کل نفرات')),
                ('total_area', models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ کل')),
                ('final_person_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ نهایی')),
                ('total_charge_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ کل ماهانه')),
                ('send_notification', models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='')),
                ('transaction_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('details', models.CharField(blank=True, max_length=4000, null=True, verbose_name='')),
                ('civil_charge', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ عمرانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('person_area_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_area_charge', to='admin_panel.chargebypersonarea')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_by_person_area', to='user_app.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_by_person_area', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
