# Generated by Django 5.2 on 2025-05-31 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0083_remove_chargebyfixpersonarea_area_charge_and_more'),
        ('user_app', '0027_alter_unit_owner_mobile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeFixVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='')),
                ('salary_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه حقوق و دستمزد')),
                ('elevator_cost_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه  آسانسور')),
                ('extra_parking_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه پارکینگ اضافه')),
                ('public_electricity_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه برق عمومی')),
                ('common_expenses_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه های سالیانه عمومی(روشنایی،نظافت و ...)')),
                ('facility_cost_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه سالیانه تاسیسات')),
                ('extinguished_cost_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه سالیانه آتش نشانس')),
                ('camera_cost_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه سالیانه دوربین')),
                ('insurance_cost_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه سالیانه بیمه')),
                ('office_cost_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه اداری و دفتری')),
                ('green_space_cost_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه فضای سبز')),
                ('public_water_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه آب مشاع')),
                ('public_gas_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه گاز مشاع')),
                ('total_area', models.PositiveIntegerField(blank=True, null=True)),
                ('total_people', models.PositiveIntegerField(blank=True, null=True)),
                ('civil', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='شارژ عمرانی')),
                ('details', models.CharField(blank=True, max_length=4000, null=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='areachargecalc',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر با پیامک'),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonareacalc',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر با پیامک'),
        ),
        migrations.AddField(
            model_name='chargebypersonareacalc',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر با پیامک'),
        ),
        migrations.AddField(
            model_name='fixareachargecalc',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر با پیامک'),
        ),
        migrations.AddField(
            model_name='fixpersonchargecalc',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر با پیامک'),
        ),
        migrations.AddField(
            model_name='personchargecalc',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر با پیامک'),
        ),
        migrations.CreateModel(
            name='ChargeFixVariableCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شارژ')),
                ('fix_charge', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ ثابت')),
                ('unit_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد واحدها')),
                ('total_people', models.PositiveIntegerField(blank=True, null=True, verbose_name=' کل نفرات')),
                ('total_area', models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ کل')),
                ('unit_fix_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ ثابت')),
                ('unit_variable_amount_person', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ متغیر هر نفر')),
                ('unit_variable_amount_area', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ متغیر هر متر')),
                ('elevator_fix_cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه 60% آسانسور')),
                ('elevator_variable_cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه 40% آسانسور')),
                ('total_charge_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ کل ماهانه')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه حقوق و دستمزد')),
                ('extra_parking', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه پارکینگ اضافه')),
                ('elevator_cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه  آسانسور')),
                ('public_electricity', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه برق عمومی')),
                ('common_expenses', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه های سالیانه عمومی(روشنایی،نظافت و ...)')),
                ('facility_cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه سالیانه تاسیسات')),
                ('extinguished_cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه سالیانه آتش نشانس')),
                ('camera_cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه سالیانه دوربین')),
                ('insurance_cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه سالیانه بیمه')),
                ('office_cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه اداری و دفتری')),
                ('green_space_cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه فضای سبز')),
                ('public_water', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه آب مشاع')),
                ('public_gas', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه گاز مشاع')),
                ('civil_charge', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه عمرانی')),
                ('details', models.CharField(blank=True, max_length=4000, null=True, verbose_name='')),
                ('send_notification', models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر')),
                ('send_sms', models.BooleanField(default=False, verbose_name='اعلام شارژ به کاربر با پیامک')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='')),
                ('transaction_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_charge', to='admin_panel.expense')),
                ('fix_variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fix_variable_charge', to='admin_panel.chargefixvariable')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_calc_fix', to='user_app.unit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_calc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ChargeCalcFixVariable',
        ),
    ]
