# Generated by Django 5.2 on 2025-05-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0084_chargefixvariable_areachargecalc_send_sms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargefixvariablecalc',
            old_name='unit_fix_amount',
            new_name='unit_fix_charge',
        ),
        migrations.RenameField(
            model_name='chargefixvariablecalc',
            old_name='unit_variable_amount_area',
            new_name='unit_variable_area_charge',
        ),
        migrations.RenameField(
            model_name='chargefixvariablecalc',
            old_name='unit_variable_amount_person',
            new_name='unit_variable_person_charge',
        ),
        migrations.AddField(
            model_name='chargefixvariable',
            name='unit_fix_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ ثابت'),
        ),
        migrations.AddField(
            model_name='chargefixvariable',
            name='unit_variable_area_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ متغیر هر متر'),
        ),
        migrations.AddField(
            model_name='chargefixvariable',
            name='unit_variable_person_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ متغیر هر نفر'),
        ),
    ]
