# Generated by Django 5.2 on 2025-05-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0085_rename_unit_fix_amount_chargefixvariablecalc_unit_fix_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargebyfixpersonarea',
            name='parking_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد پارکینگ اضافه'),
        ),
        migrations.AddField(
            model_name='chargebyfixpersonareacalc',
            name='parking_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد پارکینگ اضافه'),
        ),
    ]
