# Generated by Django 5.2 on 2025-05-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0086_chargebyfixpersonarea_parking_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargebyfixpersonareacalc',
            name='parking_count',
        ),
        migrations.AddField(
            model_name='chargefixvariable',
            name='elevator_fix_cost_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه 60% آسانسور'),
        ),
        migrations.AddField(
            model_name='chargefixvariable',
            name='elevator_variable_cost_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه 40% آسانسور'),
        ),
        migrations.AddField(
            model_name='chargefixvariable',
            name='parking_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد پارکینگ اضافه'),
        ),
    ]
