# Generated by Django 5.2 on 2025-05-31 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0087_remove_chargebyfixpersonareacalc_parking_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='camera_cost',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='civil_charge',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='common_expenses',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='details',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='elevator_cost',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='extinguished_cost',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='extra_parking',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='facility_cost',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='green_space_cost',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='insurance_cost',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='office_cost',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='public_electricity',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='public_gas',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='public_water',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='salary',
        ),
    ]
