# Generated by Django 5.2 on 2025-05-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0088_remove_chargefixvariablecalc_camera_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargefixvariablecalc',
            old_name='fix_variable',
            new_name='fix_variable_charge',
        ),
        migrations.RenameField(
            model_name='chargefixvariablecalc',
            old_name='unit_fix_charge',
            new_name='unit_fix_charge_per_unit',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='camera_cost_amount',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='common_expenses_amount',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='elevator_cost_amount',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='elevator_fix_cost_amount',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='elevator_variable_cost_amount',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='extinguished_cost_amount',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='facility_cost_amount',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='green_space_cost_amount',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='insurance_cost_amount',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='office_cost_amount',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='parking_count',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='public_electricity_amount',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='public_gas_amount',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='public_water_amount',
        ),
        migrations.RemoveField(
            model_name='chargefixvariable',
            name='salary_amount',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='elevator_fix_cost',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='elevator_variable_cost',
        ),
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='expense',
        ),
        migrations.AddField(
            model_name='chargefixvariablecalc',
            name='final_person_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ شارژ نهایی'),
        ),
    ]
