# Generated by Django 5.2 on 2025-05-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0089_rename_fix_variable_chargefixvariablecalc_fix_variable_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargefixvariable',
            name='other_cost_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
