# Generated by Django 5.2 on 2025-06-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0090_chargefixvariable_other_cost_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargefixvariablecalc',
            name='civil_charge',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شارژ عمرانی'),
        ),
        migrations.AddField(
            model_name='chargefixvariablecalc',
            name='details',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name=''),
        ),
    ]
