# Generated by Django 5.2 on 2025-06-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0091_chargefixvariablecalc_civil_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargefixvariablecalc',
            name='fix_charge',
        ),
    ]
