# Generated by Django 5.2 on 2025-06-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0092_remove_chargefixvariablecalc_fix_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargefixvariablecalc',
            name='extra_parking_charges',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
