# Generated by Django 5.2 on 2025-06-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0093_chargefixvariablecalc_extra_parking_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargefixvariablecalc',
            name='other_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
