# Generated by Django 5.2 on 2026-04-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_freerequest_alter_slidertext_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('mobile', models.CharField(max_length=100, verbose_name='')),
                ('message', models.TextField(max_length=360, verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
        ),
    ]
