# Generated by Django 5.2 on 2026-06-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_commentsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsite',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
