# Generated by Django 5.2 on 2026-04-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freerequest',
            old_name='is_done',
            new_name='is_call',
        ),
        migrations.AddField(
            model_name='freerequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
