# Generated by Django 5.2 on 2026-04-15 23:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_is_done_freerequest_is_call_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freerequest',
            name='consultant_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
