# Generated by Django 5.2 on 2026-04-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_freerequest_consultant_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freerequest',
            name='consultant_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
