# Generated by Django 5.2 on 2026-04-16 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_freerequest_consultant_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freerequest',
            name='is_read',
        ),
        migrations.CreateModel(
            name='FreeRequestReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_status_consult', to='home.freerequest')),
            ],
        ),
    ]
