# Generated by Django 5.2 on 2026-04-16 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_freerequest_is_read_freerequestreadstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeRequestReadStatus',
        ),
    ]
