# Generated by Django 5.2 on 2026-04-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_freerequestreadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
