# Generated by Django 5.2 on 2025-12-28 18:03

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='موبایل')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('otp', models.PositiveIntegerField(blank=True, null=True, verbose_name='کد فعالسازی')),
                ('otp_create_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال کد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('is_middle_admin', models.BooleanField(default=False, verbose_name='مدیر سطح میانی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_users', to=settings.AUTH_USER_MODEL, verbose_name='مدیر سطح میانی')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('charge_methods', models.ManyToManyField(blank=True, to='user_app.chargemethod', verbose_name='روش\u200cهای شارژ قابل دسترسی')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MyHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ساختمان')),
                ('user_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع کاربری')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('residents', models.ManyToManyField(blank=True, related_name='houses', to=settings.AUTH_USER_MODEL, verbose_name='ساکنین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('account_no', models.CharField(max_length=100, verbose_name='شماره حساب')),
                ('account_holder_name', models.CharField(max_length=100, verbose_name='نام صاحب حساب')),
                ('sheba_number', models.CharField(max_length=100, verbose_name='شماره شبا')),
                ('cart_number', models.CharField(max_length=100, verbose_name='شماره کارت')),
                ('initial_fund', models.PositiveIntegerField(verbose_name='موجودی اولیه صندوق')),
                ('is_default', models.BooleanField(default=False, verbose_name='حساب پیش فرض')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر (مدیر)')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banks', to='user_app.myhouse', verbose_name='ساختمان مرتبط')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(verbose_name='واحد')),
                ('unit_phone', models.CharField(blank=True, max_length=8, null=True, verbose_name='')),
                ('floor_number', models.IntegerField()),
                ('area', models.IntegerField()),
                ('bedrooms_count', models.IntegerField()),
                ('parking_number', models.CharField(blank=True, max_length=10, null=True)),
                ('parking_count', models.IntegerField()),
                ('parking_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='موقعیت پارکینگ ')),
                ('extra_parking_first', models.CharField(blank=True, max_length=100, null=True, verbose_name='موقعیت پارکینگ اول')),
                ('extra_parking_second', models.CharField(blank=True, max_length=100, null=True, verbose_name='موقعیت پارکینگ دوم')),
                ('unit_details', models.TextField(blank=True, null=True, verbose_name='توضیحات ساختمان')),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مالک')),
                ('owner_mobile', models.CharField(max_length=11, verbose_name='همراه مالک')),
                ('owner_national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
                ('owner_people_count', models.CharField(blank=True, max_length=10, null=True, verbose_name='تعداد نفرات مالک')),
                ('owner_details', models.TextField(blank=True, null=True, verbose_name='توضیحات مالک')),
                ('status_residence', models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت سکونت')),
                ('is_renter', models.BooleanField(blank=True, default=False, null=True, verbose_name=' مستاجر دارد؟')),
                ('people_count', models.IntegerField(blank=True, null=True, verbose_name='تعداد نفرات')),
                ('parking_counts', models.IntegerField(blank=True, null=True, verbose_name='تعداد پارکینگ اضافه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('first_charge_owner', models.IntegerField(blank=True, default=0, null=True, verbose_name='شارژ اولیه مالک')),
                ('owner_payment_date', models.DateField(blank=True, null=True)),
                ('owner_transaction_no', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'واحد',
                'verbose_name_plural': 'واحدها',
                'unique_together': {('user', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مستاجر')),
                ('renter_mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='همراه')),
                ('renter_national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('renter_people_count', models.CharField(blank=True, max_length=10, null=True, verbose_name='تعداد نفرات')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع اجاره')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان اجاره')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره قرارداد')),
                ('estate_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مشاور املاک')),
                ('first_charge_renter', models.IntegerField(blank=True, default=0, null=True, verbose_name='شارژ اولیه مستاجر')),
                ('renter_details', models.TextField(blank=True, null=True, verbose_name='توضیحات مستاجر')),
                ('renter_payment_date', models.DateField(blank=True, null=True)),
                ('renter_transaction_no', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('renter_is_active', models.BooleanField(default=True, verbose_name='')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renters', to='user_app.unit', verbose_name='واحد')),
            ],
        ),
        migrations.CreateModel(
            name='UnitResidenceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_type', models.CharField(choices=[('owner', 'مالک'), ('renter', 'مستاجر')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('people_count', models.IntegerField(default=0)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_residence_changes', to=settings.AUTH_USER_MODEL)),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.renter')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residence_histories', to='user_app.unit')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year', 'month', 'day')},
            },
        ),
    ]
