# Generated by Django 5.2 on 2025-04-15 19:16

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='موبایل')),
                ('username', models.CharField(max_length=11, verbose_name='نام کاربری')),
                ('otp', models.PositiveIntegerField(blank=True, null=True, verbose_name='کد فعالسازی')),
                ('otp_create_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='unitRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(verbose_name='واحد')),
                ('floor_number', models.IntegerField()),
                ('area', models.IntegerField()),
                ('bedrooms_count', models.IntegerField()),
                ('people_count', models.IntegerField()),
                ('parking_number', models.IntegerField()),
                ('parking_count', models.IntegerField()),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مالک')),
                ('owner_mobile', models.CharField(max_length=11, unique=True, verbose_name='همراه مالک')),
                ('owner_national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='')),
                ('renter_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مستاجر')),
                ('renter_mobile', models.CharField(max_length=11, unique=True, verbose_name='همراه مستاجر')),
                ('renter_national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع اجاره')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان اجاره')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره قرارداد')),
                ('estate_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مشاور املاک')),
                ('first_charge', models.IntegerField(blank=True, null=True, verbose_name='شارژ اولیه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
