# Generated by Django 5.2 on 2025-12-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhouse',
            name='floor_counts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='myhouse',
            name='unit_counts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
