# Generated by Django 5.2 on 2026-06-11 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_type', models.CharField(choices=[('zarinpal', 'زرین پال'), ('idpay', 'آیدی پی'), ('zibal', 'زیبال'), ('mellat', 'بانک ملت')], max_length=50)),
                ('merchant_id', models.CharField(max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='user_app.myhouse')),
            ],
        ),
    ]
