# Generated by Django 5.2 on 2025-06-03 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_paymoney_bank_alter_receivemoney_bank'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='house_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام ساختمان'),
        ),
        migrations.AddField(
            model_name='bank',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MyHouse',
        ),
    ]
