# Generated by Django 5.2 on 2026-05-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargemethod',
            name='code',
        ),
    ]
