# Generated by Django 5.2 on 2026-01-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renter',
            old_name='bank',
            new_name='renter_bank',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='bank',
            new_name='owner_bank',
        ),
    ]
