# Generated by Django 5.2 on 2025-11-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='unit',
            name='is_renter',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=' مستاجر دارد؟'),
        ),
    ]
