# Generated by Django 5.2 on 2026-05-28 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_chargemethod_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myhouse',
            name='user',
        ),
        migrations.AddField(
            model_name='myhouse',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='managed_houses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_users', to='user_app.myhouse', verbose_name='ساختمان'),
        ),
    ]
