# Generated by Django 5.2 on 2025-04-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_unit_people_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='first_charge',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='شارژ اولیه'),
        ),
    ]
