# Generated by Django 5.2 on 2025-11-07 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_unit_is_owner_unit_is_renter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ساختمان')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('account_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.bank', verbose_name='شماره حساب')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_houses', to=settings.AUTH_USER_MODEL, verbose_name='مدیر ساختمان')),
                ('members', models.ManyToManyField(blank=True, related_name='houses', to=settings.AUTH_USER_MODEL, verbose_name='اعضای ساختمان')),
            ],
            options={
                'verbose_name': 'ساختمان',
                'verbose_name_plural': 'ساختمان\u200cها',
            },
        ),
    ]
