# Generated by Django 5.2 on 2026-06-11 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_housepaymentgateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('html_code', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='user_app.myhouse')),
            ],
        ),
    ]
