# Generated by Django 5.2 on 2026-01-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_bank_renter_renter_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='renter_transaction_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='owner_transaction_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
