# Generated by Django 5.2 on 2026-01-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_renter_renter_transaction_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='owner_people_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد نفرات مالک'),
        ),
    ]
