# Generated by Django 5.2 on 2026-05-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_myhouse_user_myhouse_manager_user_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myhouse',
            name='phone',
        ),
    ]
