# Generated by Django 5.2 on 2025-04-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_unit_first_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='renter_national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.IntegerField(verbose_name='واحد'),
        ),
    ]
