# Generated by Django 5.2 on 2026-06-11 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_houselicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselicense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houselicense',
            name='license_type',
            field=models.CharField(choices=[('enamad', 'اینماد'), ('samandehi', 'ساماندهی'), ('business', 'جواز کسب')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
