# Generated by Django 5.2 on 2025-11-07 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_myhouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myhouse',
            options={},
        ),
        migrations.RemoveField(
            model_name='bank',
            name='house_name',
        ),
        migrations.AddField(
            model_name='bank',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banks', to='user_app.myhouse', verbose_name='ساختمان مرتبط'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_no',
            field=models.CharField(max_length=100, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='initial_fund',
            field=models.PositiveIntegerField(verbose_name='موجودی اولیه صندوق'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر (مدیر)'),
        ),
    ]
