# Generated by Django 5.2 on 2025-04-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_unit_renter_national_code_alter_unit_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='renter_mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='همراه'),
        ),
    ]
