# Generated by Django 5.2 on 2026-06-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_houselicense_created_at_houselicense_license_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HouseLicense',
        ),
    ]
