# Generated by Django 5.2 on 2025-11-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_myhouse_options_remove_bank_house_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myhouse',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='myhouse',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='myhouse',
            name='members',
        ),
        migrations.AddField(
            model_name='myhouse',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='myhouse',
            name='user_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع کاربری'),
        ),
    ]
