# Generated by Django 5.2 on 2026-01-25 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_unit_owner_people_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='myhouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='user_app.myhouse'),
        ),
    ]
