# Generated by Django 5.2 on 2026-05-28 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_remove_myhouse_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myhouse',
            old_name='boss_mobile',
            new_name='phone',
        ),
    ]
