# Generated by Django 5.2 on 2025-04-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_unit_renter_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='first_charge',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='شارژ اولیه'),
        ),
    ]
