# Generated by Django 5.2 on 2026-01-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_unit_myhouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='is_gateway',
            field=models.BooleanField(default=False, verbose_name='حساب پیش فرض درگاه اینترنتی'),
        ),
    ]
