# Generated by Django 5.2 on 2026-05-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_rename_boss_mobile_myhouse_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myhouse',
            old_name='manager',
            new_name='user',
        ),
    ]
