# Generated by Django 5.2 on 2026-06-11 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_delete_houselicense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myhouse',
            name='enamad_code',
        ),
        migrations.AddField(
            model_name='myhouse',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='myhouse',
            name='gateway_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myhouse',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='HouseLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('enamad', 'اینماد'), ('samandehi', 'ساماندهی'), ('business', 'جواز کسب')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('html_code', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='user_app.myhouse')),
            ],
        ),
        migrations.DeleteModel(
            name='HousePaymentGateway',
        ),
    ]
