# Generated by Django 5.2 on 2025-11-18 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_myhouse_account_number_remove_myhouse_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhouse',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
