# Generated by Django 5.2 on 2025-04-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_unit_first_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='other_details',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
