# Generated by Django 5.2 on 2025-11-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_myhouse_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'واحد', 'verbose_name_plural': 'واحدها'},
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.IntegerField(verbose_name='واحد'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('user', 'unit')},
        ),
    ]
