# Generated by Django 5.2 on 2026-05-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_rename_manager_myhouse_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myhouse',
            name='residents',
        ),
    ]
