# Generated by Django 5.2 on 2026-06-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_remove_myhouse_enamad_code_myhouse_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouse',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='myhouse',
            name='gateway_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع درگاه'),
        ),
        migrations.AlterField(
            model_name='myhouse',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Merchant ID'),
        ),
    ]
