# Generated by Django 5.2 on 2026-01-28 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_bank_is_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_payer_name', models.CharField(max_length=200, verbose_name='پرداخت کننده')),
                ('description', models.CharField(max_length=4000, verbose_name='شرح')),
                ('amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ')),
                ('details', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_paid_money', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده/ نشده')),
                ('transaction_reference', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPayDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='images/user_payment/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user_app.userpaymoney')),
            ],
        ),
    ]
