# Generated by Django 5.2 on 2026-05-29 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_remove_myhouse_residents'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhouse',
            name='residents',
            field=models.ManyToManyField(blank=True, related_name='houses', to=settings.AUTH_USER_MODEL, verbose_name='ساکنین'),
        ),
    ]
