# Generated by Django 5.2 on 2026-06-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_myhouse_api_key_alter_myhouse_gateway_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myhouse',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='myhouse',
            name='gateway_type',
        ),
        migrations.RemoveField(
            model_name='myhouse',
            name='merchant_id',
        ),
        migrations.CreateModel(
            name='HousePaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_type', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('idpay', 'آی\u200cدی\u200cپی'), ('nextpay', 'نکست\u200cپی'), ('stripe', 'Stripe')], max_length=50, verbose_name='نوع درگاه')),
                ('merchant_id', models.CharField(max_length=255, verbose_name='Merchant ID')),
                ('api_key', models.CharField(max_length=500, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_sandbox', models.BooleanField(default=False, verbose_name='حالت تست')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='user_app.myhouse')),
            ],
        ),
    ]
