# Generated by Django 5.2 on 2025-04-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_unit_other_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='other_details',
        ),
        migrations.AddField(
            model_name='unit',
            name='owner_details',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات مالک'),
        ),
        migrations.AddField(
            model_name='unit',
            name='renter_details',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات مستاجر'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_details',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات ساختمان'),
        ),
    ]
