# Generated by Django 5.2 on 2026-01-28 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_userpaymoney_userpaydocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymoney',
            name='is_paid_money',
        ),
        migrations.RemoveField(
            model_name='userpaymoney',
            name='user_payer_name',
        ),
        migrations.AddField(
            model_name='userpaymoney',
            name='payer_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userpaymoney',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='userpaymoney',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='userpaymoney',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UserPayMoneyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='images/user_pay/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user_app.userpaymoney')),
            ],
        ),
        migrations.DeleteModel(
            name='UserPayDocument',
        ),
    ]
