# Generated by Django 5.2 on 2025-11-19 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_unit_options_alter_unit_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_house_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
