# Generated by Django 5.2 on 2026-06-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_myhouse_api_key_remove_myhouse_gateway_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houselicense',
            name='title',
        ),
    ]
