# Generated by Django 5.2 on 2026-01-28 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_userpaymoney_is_paid_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymoney',
            name='register_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ سند'),
            preserve_default=False,
        ),
    ]
