# Generated by Django 5.2 on 2025-05-05 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_unit_other_details_unit_owner_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('account_no', models.CharField(max_length=100, verbose_name='شماره حساب ')),
                ('account_name', models.CharField(max_length=100, verbose_name='نام صاحب حساب')),
                ('sheba_number', models.CharField(max_length=100, verbose_name='شماره شبا')),
                ('cart_number', models.CharField(max_length=100, verbose_name='شماره کارت')),
                ('initial_fund', models.CharField(max_length=100, verbose_name='موجود اولیه صندوق')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
        ),
        migrations.RemoveField(
            model_name='myhouse',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='myhouse',
            name='cart_name',
        ),
        migrations.RemoveField(
            model_name='myhouse',
            name='cart_no',
        ),
        migrations.RemoveField(
            model_name='myhouse',
            name='initial_fund',
        ),
        migrations.AlterField(
            model_name='myhouse',
            name='account_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
    ]
