# Generated by Django 5.2 on 2026-05-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_myhouse_residents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='parking_count',
        ),
    ]
