# Generated by Django 5.2 on 2025-11-20 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_myhouse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhouse',
            name='residents',
            field=models.ManyToManyField(blank=True, related_name='houses', to=settings.AUTH_USER_MODEL, verbose_name='ساکنین'),
        ),
        migrations.AlterField(
            model_name='myhouse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
