# Generated by Django 5.2 on 2026-06-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_remove_houselicense_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepaymentgateway',
            name='gateway_type',
            field=models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('idpay', 'آی\u200cدی\u200cپی'), ('nextpay', 'نکست\u200cپی'), ('stripe', 'Stripe'), ('mellat', 'به پرداخت ملت')], max_length=50, verbose_name='نوع درگاه'),
        ),
    ]
