# Generated by Django 5.2 on 2026-01-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_userpaymoney_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymoney',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
