# Generated by Django 5.2 on 2025-05-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_bank_remove_myhouse_account_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='account_name',
            new_name='account_holder_name',
        ),
    ]
