# Generated by Django 5.2 on 2025-12-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_myhouse_residents_alter_myhouse_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
            ],
        ),
    ]
