# Generated by Django 5.2 on 2026-01-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_userpaymoney_payment_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_resident',
            field=models.BooleanField(default=False, verbose_name='ساکن ساختمان'),
        ),
    ]
