# Generated by Django 5.2 on 2025-12-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_chargemethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='charge_methods',
            field=models.ManyToManyField(blank=True, to='user_app.chargemethod', verbose_name='روش\u200cهای شارژ قابل دسترسی'),
        ),
    ]
