# Generated by Django 5.2 on 2025-05-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_rename_account_name_bank_account_holder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='initial_fund',
            field=models.PositiveIntegerField(max_length=100, verbose_name='موجود اولیه صندوق'),
        ),
    ]
