# Generated by Django 5.2 on 2025-05-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_bank_initial_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='initial_fund',
            field=models.PositiveIntegerField(verbose_name='موجود اولیه صندوق'),
        ),
    ]
