# Generated by Django 5.2 on 2026-02-10 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_user_is_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymoney',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pay_money', to='user_app.myhouse'),
        ),
    ]
