# Generated by Django 5.2 on 2025-12-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_calendarnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='حساب پیش فرض'),
        ),
    ]
