# Generated by Django 5.2 on 2026-02-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_userpaymoney_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='initial_fund',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='موجودی اولیه صندوق'),
        ),
    ]
