# Generated by Django 5.2 on 2025-05-05 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_alter_bank_initial_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouse',
            name='account_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.bank', verbose_name='شماره حساب'),
        ),
    ]
