# Generated by Django 5.2 on 2026-02-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_alter_bank_initial_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_unit',
            field=models.BooleanField(default=False, verbose_name=' ساکن ساختمان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_resident',
            field=models.BooleanField(default=False, verbose_name='مدیر ساکن ساختمان'),
        ),
    ]
