# Generated by Django 5.2 on 2025-12-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_bank_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='first_charge',
        ),
        migrations.AddField(
            model_name='renter',
            name='first_charge_renter',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='شارژ اولیه مستاجر'),
        ),
        migrations.AddField(
            model_name='unit',
            name='first_charge_owner',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='شارژ اولیه مالک'),
        ),
    ]
