# Generated by Django 5.2 on 2025-05-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_alter_myhouse_account_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='name',
            new_name='bank_name',
        ),
    ]
