# Generated by Django 5.2 on 2025-05-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_rename_name_bank_bank_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myhouse',
            old_name='account_no',
            new_name='account_number',
        ),
    ]
