# Generated by Django 5.2 on 2025-12-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_remove_renter_first_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.bank', verbose_name='شماره حساب'),
        ),
    ]
