# Generated by Django 5.2 on 2026-02-12 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_user_is_unit_alter_user_is_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='myhouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renters', to='user_app.myhouse'),
        ),
    ]
