# Generated by Django 5.2 on 2025-05-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_rename_account_no_myhouse_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=''),
        ),
    ]
