# Generated by Django 5.2 on 2026-02-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_renter_myhouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargemethod',
            name='code',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
