# Generated by Django 5.2 on 2025-05-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_alter_myhouse_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='people_count',
            new_name='renter_people_count',
        ),
        migrations.AddField(
            model_name='unit',
            name='owner_people_count',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تعداد نفرات مالک'),
        ),
    ]
