# Generated by Django 5.2 on 2026-02-13 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_chargemethod_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitresidencehistory',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residence_histories', to='user_app.unit'),
        ),
    ]
