# Generated by Django 5.2 on 2025-12-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_renter_bank_renter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=''),
        ),
    ]
