# Generated by Django 5.2 on 2025-05-12 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_rename_people_count_unit_renter_people_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='estate_name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='first_charge',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='renter_details',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='renter_mobile',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='renter_name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='renter_national_code',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='renter_people_count',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='start_date',
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مستاجر')),
                ('renter_mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='همراه')),
                ('renter_national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('renter_people_count', models.CharField(blank=True, max_length=10, null=True, verbose_name='تعداد نفرات')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع اجاره')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان اجاره')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره قرارداد')),
                ('estate_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مشاور املاک')),
                ('first_charge', models.IntegerField(blank=True, default=0, null=True, verbose_name='شارژ اولیه')),
                ('renter_details', models.TextField(blank=True, null=True, verbose_name='توضیحات مستاجر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.unit', verbose_name='')),
            ],
        ),
    ]
