# Generated by Django 5.2 on 2026-02-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_alter_unitresidencehistory_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trail',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
