# Generated by Django 5.2 on 2025-12-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_renter_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='is_active',
        ),
    ]
