# Generated by Django 5.2 on 2026-02-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_user_is_trail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_trail',
            new_name='is_trial',
        ),
    ]
