# Generated by Django 5.2 on 2025-05-12 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_remove_unit_contract_number_remove_unit_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.unit', verbose_name='renters'),
        ),
    ]
