# Generated by Django 5.2 on 2025-12-23 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_remove_renter_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renter',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
