# Generated by Django 5.2 on 2025-05-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_alter_renter_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='unit',
        ),
        migrations.AddField(
            model_name='unit',
            name='renters',
            field=models.ManyToManyField(related_name='units', to='user_app.renter'),
        ),
    ]
