# Generated by Django 5.2 on 2025-12-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_renter_payment_date_renter_transaction_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
