# Generated by Django 5.2 on 2026-02-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_rename_is_trail_user_is_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhouse',
            name='subdomain',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='زیردامنه'),
        ),
    ]
