# Generated by Django 5.2 on 2025-05-12 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_remove_renter_unit_unit_renters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='renters',
        ),
        migrations.AddField(
            model_name='renter',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='user_app.unit', verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.CharField(max_length=10, unique=True, verbose_name='واحد'),
        ),
    ]
