# Generated by Django 5.2 on 2026-02-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_myhouse_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhouse',
            name='enamad_code',
            field=models.TextField(blank=True, null=True, verbose_name='کد اینماد'),
        ),
    ]
