# Generated by Django 5.2 on 2025-12-24 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_unitownerhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitResidenceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_type', models.CharField(choices=[('owner', 'مالک'), ('renter', 'مستاجر')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('people_count', models.IntegerField(default=0)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_residence_changes', to=settings.AUTH_USER_MODEL)),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.renter')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residence_histories', to='user_app.unit')),
            ],
        ),
        migrations.DeleteModel(
            name='UnitOwnerHistory',
        ),
    ]
