# Generated by Django 5.2 on 2025-05-12 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_remove_unit_renters_renter_unit_alter_unit_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renters', to='user_app.unit', verbose_name='واحد'),
        ),
    ]
