# Generated by Django 5.2 on 2026-02-26 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_myhouse_enamad_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhouse',
            name='boss_mobile',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouse',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
