# Generated by Django 5.2 on 2026-02-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_myhouse_boss_mobile_myhouse_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myhouse',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
