# Generated by Django 5.2 on 2025-05-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_alter_renter_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renter',
            old_name='is_active',
            new_name='renter_is_active',
        ),
    ]
