# Generated by Django 5.2 on 2025-12-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_unitresidencehistory_delete_unitownerhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renter',
            old_name='payment_date',
            new_name='renter_payment_date',
        ),
        migrations.RenameField(
            model_name='renter',
            old_name='transaction_no',
            new_name='renter_transaction_no',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='payment_date',
            new_name='owner_payment_date',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='transaction_no',
            new_name='owner_transaction_no',
        ),
    ]
