# Generated by Django 5.2 on 2025-05-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0023_rename_is_active_renter_renter_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='people_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد نفرات'),
        ),
    ]
