# Generated by Django 5.2 on 2026-05-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0023_rename_phone_number_myhouse_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
    ]
