# Generated by Django 5.2 on 2025-05-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0024_unit_people_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='واحد'),
        ),
    ]
