# Generated by Django 5.2 on 2025-05-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0025_alter_unit_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.IntegerField(default=123, unique=True, verbose_name='واحد'),
            preserve_default=False,
        ),
    ]
