# Generated by Django 5.2 on 2025-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0026_alter_unit_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='owner_mobile',
            field=models.CharField(max_length=11, verbose_name='همراه مالک'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='owner_national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
    ]
