# Generated by Django 5.2 on 2025-05-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0027_alter_unit_owner_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='extra_parking_second',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='موقعیت پارکینگ دوم'),
        ),
        migrations.AddField(
            model_name='unit',
            name='parking_counts',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد پارکینگ اضافه'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parking_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='موقعیت پارکینگ اول'),
        ),
    ]
