# Generated by Django 5.2 on 2025-05-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0028_unit_extra_parking_second_unit_parking_counts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='extra_parking_first',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='موقعیت پارکینگ اول'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parking_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='موقعیت پارکینگ '),
        ),
    ]
