# Generated by Django 5.2 on 2026-05-05 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0023_rename_phone_number_myhouse_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('poll_type', models.CharField(choices=[('yesno', 'بلی / خیر'), ('multi', 'چند گزینه\u200cای')], default='yesno', max_length=10, verbose_name='نوع نظرسنجی')),
                ('start_date', models.DateTimeField(verbose_name='شروع')),
                ('end_date', models.DateTimeField(verbose_name='پایان')),
                ('is_secret', models.BooleanField(default=False, verbose_name='آیا رأی مخفی باشد؟')),
                ('restrict_to_active_residents', models.BooleanField(default=True, verbose_name='محدود به ساکنین فعال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='user_app.myhouse', verbose_name='ساختمان')),
            ],
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='متن گزینه')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls_app.poll', verbose_name='نظرسنجی')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls_app.pollchoice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls_app.poll')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='user_app.unit', verbose_name='واحد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='رای دهنده')),
            ],
            options={
                'verbose_name': 'رای',
                'verbose_name_plural': 'آرا',
                'unique_together': {('poll', 'unit')},
            },
        ),
    ]
