# Generated by Django 5.2 on 2025-12-28 18:03

import ckeditor_uploader.fields
import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('ticket_no', models.PositiveIntegerField(default=notifications.models.generate_ticket_no, editable=False, unique=True)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('answer_message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False, verbose_name='')),
                ('is_read', models.BooleanField(default=False, verbose_name='')),
                ('is_call', models.BooleanField(default=False, verbose_name='تماس گرفته شده')),
                ('is_closed', models.BooleanField(default=False, verbose_name='فعال')),
                ('is_answer', models.BooleanField(default=False, verbose_name='')),
                ('is_waiting', models.BooleanField(default=False, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminTicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='admin_ticket_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MiddleAdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='support_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SupportUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('ticket_no', models.PositiveIntegerField(default=notifications.models.generate_ticket_no, editable=False, unique=True)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('answer_message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False, verbose_name='')),
                ('is_read', models.BooleanField(default=False, verbose_name='')),
                ('is_call', models.BooleanField(default=False, verbose_name='تماس گرفته شده')),
                ('is_closed', models.BooleanField(default=False, verbose_name='فعال')),
                ('is_answer', models.BooleanField(default=False, verbose_name='')),
                ('is_waiting', models.BooleanField(default=False, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
