# Generated by Django 5.2 on 2025-11-18 21:20

import ckeditor_uploader.fields
import django.db.models.deletion
import notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='support_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('ticket_no', models.PositiveIntegerField(default=notifications.models.generate_ticket_no, editable=False, unique=True)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('answer_message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False, verbose_name='')),
                ('is_read', models.BooleanField(default=False, verbose_name='')),
                ('is_call', models.BooleanField(default=False, verbose_name='تماس گرفته شده')),
                ('is_closed', models.BooleanField(default=False, verbose_name='فعال')),
                ('is_answer', models.BooleanField(default=False, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('attachments', models.ManyToManyField(blank=True, to='notifications.supportfile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('support_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notifications.supportuser')),
            ],
        ),
        migrations.AddField(
            model_name='supportfile',
            name='support_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='notifications.supportuser'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.supportuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
