# Generated by Django 5.2 on 2025-11-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportfile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='support_files/'),
        ),
    ]
