# Generated by Django 5.2 on 2026-01-23 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminticket',
            name='middle_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_ticket_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminticketfile',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_ticket', to='notifications.adminticket'),
        ),
        migrations.AddField(
            model_name='adminticketmessage',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='notifications.adminticketfile'),
        ),
        migrations.AddField(
            model_name='adminticketmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_ticket_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notifications.adminticket'),
        ),
        migrations.AddField(
            model_name='middleadminnotification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.adminticket'),
        ),
        migrations.AddField(
            model_name='middleadminnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middleAdmin_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='notifications.supportfile'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='support_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notifications.supportuser'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='support_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='notifications.supportuser'),
        ),
        migrations.AddField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.supportuser'),
        ),
    ]
