# Generated by Django 5.2 on 2026-02-09 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        ('user_app', '0011_user_is_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportuser',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_users', to='user_app.myhouse'),
        ),
    ]
