# Generated by Django 5.2 on 2025-11-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_supportfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='attachments',
            field=models.ManyToManyField(blank=True, null=True, to='notifications.supportfile'),
        ),
    ]
