# Generated by Django 5.2 on 2026-02-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_adminticket_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportuser',
            name='house',
        ),
    ]
