# Generated by Django 5.2 on 2025-11-20 16:43

import ckeditor_uploader.fields
import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_adminticketfile_adminticket_adminticketmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminticket',
            name='subject',
        ),
        migrations.AddField(
            model_name='adminticket',
            name='answer_message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminticket',
            name='is_answer',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='adminticket',
            name='is_call',
            field=models.BooleanField(default=False, verbose_name='تماس گرفته شده'),
        ),
        migrations.AddField(
            model_name='adminticket',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='adminticket',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='adminticket',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminticket',
            name='ticket_no',
            field=models.PositiveIntegerField(default=notifications.models.generate_ticket_no, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='adminticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adminticket',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
    ]
