# Generated by Django 5.2 on 2025-11-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_middleadminnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminticket',
            old_name='creator',
            new_name='user',
        ),
    ]
