# Generated by Django 5.2 on 2025-11-20 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_rename_creator_adminticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminticketfile',
            name='middle_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files_ticket', to='notifications.supportuser'),
            preserve_default=False,
        ),
    ]
