# Generated by Django 5.2 on 2025-11-20 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_adminticketfile_middle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminticketfile',
            name='middle_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_ticket', to='notifications.adminticket'),
        ),
    ]
