# Generated by Django 5.2 on 2025-11-20 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_alter_adminticketfile_middle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middleadminnotification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.adminticket'),
        ),
    ]
