# Generated by Django 5.2 on 2025-11-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_alter_middleadminnotification_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminticketfile',
            old_name='middle_user',
            new_name='ticket',
        ),
    ]
