# Generated by Django 5.2 on 2025-11-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_rename_middle_user_adminticketfile_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminticket',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان'),
        ),
    ]
