# Generated by Django 5.2 on 2025-11-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_adminticket_middle_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminticket',
            name='is_waiting',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
