# Generated by Django 5.2 on 2025-11-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_adminticket_is_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportuser',
            name='is_waiting',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
